import {
  TemplateBlock,
  HeroBlockContent,
  FeaturesBlockContent,
  CTABlockContent,
  TestimonialsBlockContent,
  FAQBlockContent,
  PricingBlockContent,
  BeforeAfterBlockContent,
  ProblemBlockContent,
  BonusListBlockContent,
  GuaranteeBlockContent,
  CountdownBlockContent,
  InlineCTABlockContent,
  TemplateThemeKey,
} from '@/types/templates';

export type ColorThemeKey = TemplateThemeKey;

interface ThemeDefinition {
  primary: string;
  secondary?: string;
  accent: string;
  background: string;
  text: string;
  name: string;
  description: string;
}

export const COLOR_THEMES: Record<ColorThemeKey, ThemeDefinition> = {
  power_blue: {
    primary: '#1E40AF',
    secondary: '#3B82F6',
    accent: '#60A5FA',
    background: '#111827',
    text: '#FFFFFF',
    name: 'パワーブルー',
    description: '学習・資格取得に最適',
  },
  urgent_red: {
    primary: '#DC2626',
    secondary: '#EF4444',
    accent: '#F59E0B',
    background: '#111827',
    text: '#FFFFFF',
    name: '緊急レッド',
    description: '投資・FX・副業に最適',
  },
  energy_orange: {
    primary: '#EA580C',
    secondary: '#F59E0B',
    accent: '#FBBF24',
    background: '#1F2937',
    text: '#FFFFFF',
    name: 'エネルギーオレンジ',
    description: 'ダイエット・筋トレに最適',
  },
  gold_premium: {
    primary: '#B45309',
    secondary: '#F59E0B',
    accent: '#FCD34D',
    background: '#0F172A',
    text: '#FFFFFF',
    name: 'ゴールドプレミアム',
    description: '高額商品・コンサルに最適',
  },
  passion_pink: {
    primary: '#BE185D',
    secondary: '#EC4899',
    accent: '#F472B6',
    background: '#1F2937',
    text: '#FFFFFF',
    name: 'パッションピンク',
    description: '恋愛・美容に最適',
  },
};

export const TEMPLATE_LIBRARY: TemplateBlock[] = [
  {
    id: 'top-hero-landing',
    templateId: 'top-hero-1',
    name: 'ヒーロー（情報鮮度）',
    category: 'header',
    description: 'TOPページのヒーローセクションを再現した軽量テンプレート',
    defaultContent: {
      title: '情報には鮮度がある。',
      subtitle: 'スワイプ型LP作成プラットフォームで、今すぐ情報商材を販売',
      tagline: 'NEXT LAUNCH',
      highlightText: '５分でLP公開',
      buttonText: '無料で始める',
      buttonUrl: '/register',
      secondaryButtonText: 'ログイン',
      secondaryButtonUrl: '/login',
      backgroundVideoUrl: '/videos/pixta.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#050814',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-book-flip',
    templateId: 'top-hero-1',
    name: 'ヒーロー（知識を書籍で紐解く）',
    category: 'header',
    description: '静かな書斎で本をめくる映像を背景に、研究系・教材系に最適なヒーロー。',
    defaultContent: {
      title: '体系化された知識で、最速の結果を。',
      subtitle: '研究と実践で蓄積したノウハウを、動画とテンプレで余すことなく提供します。',
      tagline: 'KNOWLEDGE LAB',
      highlightText: '実践テンプレ付き',
      buttonText: 'プログラムを試す',
      buttonUrl: '/register',
      secondaryButtonText: '資料を請求',
      secondaryButtonUrl: '/download',
      backgroundVideoUrl: '/videos/hero-book-flip.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#080B13',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-couple',
    templateId: 'top-hero-1',
    name: 'ヒーロー（カップルの未来設計）',
    category: 'header',
    description: '寄り添うカップルの映像で、恋愛・ライフスタイル商材に合うヒーロー。',
    defaultContent: {
      title: '二人の距離を縮める、最新メソッド。',
      subtitle: '心理学とデータを組み合わせたシナリオで、恋愛の悩みを解決へ。',
      tagline: 'RELATION DESIGN',
      highlightText: '90日プログラム',
      buttonText: '無料診断を受ける',
      buttonUrl: '/assessment',
      secondaryButtonText: '導入事例を見る',
      secondaryButtonUrl: '/cases',
      backgroundVideoUrl: '/videos/hero-couple.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#0B0E18',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-smartphone',
    templateId: 'top-hero-1',
    name: 'ヒーロー（スマホ操作）',
    category: 'header',
    description: 'スマホ操作の映像で、デジタル教材や自動化ツールを訴求できるヒーロー。',
    defaultContent: {
      title: 'スマホ1台で、自動収益の仕組み化。',
      subtitle: 'テンプレを選ぶだけで、LINE構築・決済・配信まで自動化できます。',
      tagline: 'MOBILE AUTOMATION',
      highlightText: '完全ノーコード',
      buttonText: '無料トライアル',
      buttonUrl: '/register',
      secondaryButtonText: '機能を見る',
      secondaryButtonUrl: '/features',
      backgroundVideoUrl: '/videos/hero-smartphone.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#050811',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-night-crossing',
    templateId: 'top-hero-1',
    name: 'ヒーロー（夜の交差点）',
    category: 'header',
    description: '都会の交差点を背景に、スピード感と勢いを演出できるヒーロー。',
    defaultContent: {
      title: '一晩で市場を席巻する、ローンチ戦略。',
      subtitle: '高速な意思決定とAI自動化で、旬な情報を一気に届ける。',
      tagline: 'NIGHT LAUNCH',
      highlightText: 'スピード配信',
      buttonText: 'ローンチを設計する',
      buttonUrl: '/register',
      secondaryButtonText: 'ロードマップを見る',
      secondaryButtonUrl: '/roadmap',
      backgroundVideoUrl: '/videos/hero-night-crossing.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#030611',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-night-road',
    templateId: 'top-hero-1',
    name: 'ヒーロー（夜の道路）',
    category: 'header',
    description: '光が流れる夜の道路映像で、投資・副業系の緊張感を演出。',
    defaultContent: {
      title: '市場の波に乗り遅れない、即断即決の情報セット。',
      subtitle: '最新の相場データを毎朝5時に配信。行動する投資家のための学習プラットフォーム。',
      tagline: 'MARKET SIGNAL',
      highlightText: '毎朝5時配信',
      buttonText: '今すぐ参加する',
      buttonUrl: '/register',
      secondaryButtonText: '説明会を見る',
      secondaryButtonUrl: '/webinar',
      backgroundVideoUrl: '/videos/hero-night-road.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#05070F',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-smoke',
    templateId: 'top-hero-1',
    name: 'ヒーロー（スモーク演出）',
    category: 'header',
    description: '幻想的な煙の映像で、ブランディング性の高い講座訴求に活用。',
    defaultContent: {
      title: '世界観で魅了する、ハイブランド講座。',
      subtitle: '空間演出やストーリーテリングを組み込んだ、プレミアムローンチパッケージ。',
      tagline: 'PREMIUM STAGE',
      highlightText: '世界観設計',
      buttonText: 'コンセプトを体験',
      buttonUrl: '/register',
      secondaryButtonText: '世界観資料を請求',
      secondaryButtonUrl: '/concept-book',
      backgroundVideoUrl: '/videos/hero-smoke.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#070710',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-beach',
    templateId: 'top-hero-1',
    name: 'ヒーロー（砂浜と海）',
    category: 'header',
    description: '穏やかな波の映像で、ライフスタイルやウェルネス訴求に適したヒーロー。',
    defaultContent: {
      title: '理想の暮らしをデザインする、習慣づくりプログラム。',
      subtitle: '時間と場所に縛られない働き方・生き方を、3ヶ月で手に入れる。',
      tagline: 'LIFESTYLE SHIFT',
      highlightText: '60日伴走',
      buttonText: '無料ウェビナーに参加',
      buttonUrl: '/webinar',
      secondaryButtonText: '受講生の体験談',
      secondaryButtonUrl: '/voices',
      backgroundVideoUrl: '/videos/hero-beach.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#061019',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-downtown',
    templateId: 'top-hero-1',
    name: 'ヒーロー（繁華街の熱量）',
    category: 'header',
    description: '繁華街のネオンと人の流れで、エネルギッシュな市場を印象づけるヒーロー。',
    defaultContent: {
      title: '熱量の高い市場で、一気に認知を獲得する。',
      subtitle: 'SNS広告と連動したローンチ設計で、初動から売上を最大化。',
      tagline: 'URBAN IMPACT',
      highlightText: 'SNSアセット付',
      buttonText: 'プロジェクトを相談',
      buttonUrl: '/contact',
      secondaryButtonText: '戦略資料をダウンロード',
      secondaryButtonUrl: '/strategy',
      backgroundVideoUrl: '/videos/hero-downtown.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#050510',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-tiger',
    templateId: 'top-hero-1',
    name: 'ヒーロー（虎の咆哮）',
    category: 'header',
    description: '虎の迫力ある映像で、自己啓発やマインドセット系に響くヒーロー。',
    defaultContent: {
      title: '内なる野性を解き放ち、圧倒的な成果へ。',
      subtitle: 'メンタルと戦略を同時に鍛えるエリート講座。勝ち続ける思考を48時間でインストール。',
      tagline: 'UNLEASH POWER',
      highlightText: '2Days集中',
      buttonText: '集中合宿に申し込む',
      buttonUrl: '/bootcamp',
      secondaryButtonText: '講師のメッセージ',
      secondaryButtonUrl: '/message',
      backgroundVideoUrl: '/videos/hero-tiger.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#080808',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-running-man',
    templateId: 'top-hero-1',
    name: 'ヒーロー（走る男性）',
    category: 'header',
    description: '走り抜ける男性の映像で、フィットネスや習慣化商材を訴求。',
    defaultContent: {
      title: '60日で体を変える、科学的トレーニング。',
      subtitle: '栄養・運動・メンタルをAIが伴走サポート。挫折ゼロのダイエットプログラム。',
      tagline: 'BODY MAKE',
      highlightText: 'パーソナルAI',
      buttonText: '無料カウンセリング',
      buttonUrl: '/trial',
      secondaryButtonText: '成功者インタビュー',
      secondaryButtonUrl: '/voices',
      backgroundVideoUrl: '/videos/hero-running-man.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#070B10',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-gold-particles',
    templateId: 'top-hero-1',
    name: 'ヒーロー（金の粒子）',
    category: 'header',
    description: '金色の粒子が舞う映像で、プレミアムな高額商品を演出するヒーロー。',
    defaultContent: {
      title: '価値が伝わる、プレミアムローンチへ。',
      subtitle: '高額講座に特化したフルファネル構築で、単価と成約率を最大化。',
      tagline: 'EXECUTIVE LAUNCH',
      highlightText: 'VIP限定',
      buttonText: '戦略セッションを予約',
      buttonUrl: '/consulting',
      secondaryButtonText: '導入実績を見る',
      secondaryButtonUrl: '/results',
      backgroundVideoUrl: '/videos/hero-gold-particles.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#0A0603',
    } as HeroBlockContent,
  },
  {
    id: 'top-highlights-grid',
    templateId: 'top-highlights-1',
    name: 'ハイライト（課題から提案へ）',
    category: 'content',
    description: '課題と解決策のセットで価値を伝えるハイライトテンプレート。',
    defaultContent: {
      title: 'こんな課題、ありませんか？',
      tagline: 'Pain Points',
      features: [
        {
          icon: '🎨',
          title: 'デザイン設計に時間を奪われる',
          description: 'ゼロから構成やビジュアルを整えるのは非効率で差別化も難しい。',
        },
        {
          icon: '🌐',
          title: 'ドメイン・サーバー整備が面倒',
          description: '取得・SSL対応まで段取りに追われ、初動が遅れる。',
        },
        {
          icon: '💳',
          title: '決済機能の実装ハードル',
          description: '安全な決済フローの準備には高い技術とセキュリティ知識が必要。',
        },
      ],
      backgroundColor: '#F1F5F9',
      textColor: '#0F172A',
      accentColor: '#2563EB',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-highlights-mint',
    templateId: 'top-highlights-1',
    name: 'ハイライト（ミント）',
    category: 'content',
    description: '爽やかなミントトーンで、ウェルネスや自己啓発向けの課題訴求に最適。',
    defaultContent: {
      title: '新しい習慣が続かない理由',
      tagline: 'Lifestyle Shift',
      features: [
        {
          icon: '🌿',
          title: '行動が三日坊主で終わる',
          description: '継続の仕組みがなく、気合と根性に頼ってしまう。',
        },
        {
          icon: '🧘‍♀️',
          title: 'メンタルの切り替えが難しい',
          description: '自分に合ったリズムを知らず、ストレスでリバウンドしてしまう。',
        },
        {
          icon: '📊',
          title: '成果が可視化できない',
          description: '感覚だけで取り組み、伸びている実感が持てずモチベが続かない。',
        },
      ],
      backgroundColor: '#E0F7F4',
      textColor: '#064E3B',
      accentColor: '#0D9488',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-highlights-amber',
    templateId: 'top-highlights-1',
    name: 'ハイライト（アンバー）',
    category: 'content',
    description: '温かみのあるアンバー配色で、ビジネスや教育商材の課題訴求に。',
    defaultContent: {
      title: 'ビジネス成長が頭打ちになる原因',
      tagline: 'Growth Issues',
      features: [
        {
          icon: '📈',
          title: '戦略が属人化している',
          description: 'トッププレイヤーのノウハウが共有されず、再現性が低い。',
        },
        {
          icon: '🧭',
          title: '改善指標が曖昧',
          description: 'KPIの設定が曖昧で、何から手を付けるべきか判断できない。',
        },
        {
          icon: '🤝',
          title: 'チーム連携が機能していない',
          description: '部署間で情報共有ができず、施策のスピードが落ちている。',
        },
      ],
      backgroundColor: '#FFF7ED',
      textColor: '#7C2D12',
      accentColor: '#F97316',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-highlights-violet',
    templateId: 'top-highlights-1',
    name: 'ハイライト（バイオレット）',
    category: 'content',
    description: '落ち着いたバイオレットで、権威性や信頼を訴求する情報商材向け。',
    defaultContent: {
      title: '学びが成果につながらない理由',
      tagline: 'Insight Points',
      features: [
        {
          icon: '🧠',
          title: '情報が頭でっかちになる',
          description: 'インプット偏重で、実践に落とし込むフレームがない。',
        },
        {
          icon: '🪜',
          title: '段階設計が不十分',
          description: '初級〜上級の橋渡しがなく、途中で挫折してしまう。',
        },
        {
          icon: '🔍',
          title: '本質的な課題が見えていない',
          description: '現状分析が甘く、施策が的外れになってしまう。',
        },
      ],
      backgroundColor: '#F3E8FF',
      textColor: '#2E1065',
      accentColor: '#8B5CF6',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-highlights-slate',
    templateId: 'top-highlights-1',
    name: 'ハイライト（モノトーン）',
    category: 'content',
    description: 'シックなモノトーンで、汎用性の高いビジネスシーン向け課題訴求。',
    defaultContent: {
      title: 'プロジェクトが停滞する兆候',
      tagline: 'Project Risks',
      features: [
        {
          icon: '🕒',
          title: '意思決定が遅い',
          description: '判断基準が不明瞭で、会議だけが増えてしまう。',
        },
        {
          icon: '🧾',
          title: 'タスクが散らばっている',
          description: '情報が複数のツールに散在し、全体最適ができていない。',
        },
        {
          icon: '🧩',
          title: '責任領域が曖昧',
          description: '誰が何をやるのか定義されず、成果が属人化している。',
        },
      ],
      backgroundColor: '#F8FAFC',
      textColor: '#111827',
      accentColor: '#475569',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-cta-gradient',
    templateId: 'top-cta-1',
    name: 'CTA（グラデーション）',
    category: 'conversion',
    description: 'TOPページ終盤の最終CTAを再現したブロック',
    defaultContent: {
      title: '今すぐ始めよう',
      subtitle: '情報には鮮度がある。５分でLPを公開して、今すぐ販売を開始。',
      buttonText: '無料で始める',
      buttonUrl: '/register',
      secondaryButtonText: 'デモを見る',
      secondaryButtonUrl: '/demo',
      backgroundColor: '#E0F2FE',
      textColor: '#0F172A',
    } as CTABlockContent,
  },
  {
    id: 'top-testimonials-trust',
    templateId: 'top-testimonials-1',
    name: 'お客様の声（2カラム）',
    category: 'trust',
    description: 'シンプルな2カラム構成で実績を伝えるテンプレート。',
    defaultContent: {
      title: 'お客様の声',
      subtitle: '導入企業や受講生のリアルな成果をご紹介します。',
      testimonials: [
        {
          quote: 'AIがコピー案を提案してくれるので、初稿制作が一気に楽になりました。初月から前年度比180%の売上です。',
          name: 'オンライン講座運営 / 佐藤様',
          role: '年間売上1.2億円',
        },
        {
          quote: 'ランディングページ制作の外注費を70%削減。自社メンバーだけで週1ペースのローンチが回せています。',
          name: 'マーケティング会社 / 山田様',
          role: 'チーム3名で運用',
        },
      ],
      backgroundColor: '#FFFFFF',
      textColor: '#0F172A',
    } as TestimonialsBlockContent,
  },
  {
    id: 'top-faq-default',
    templateId: 'top-faq-1',
    name: 'FAQ（シンプルアコーディオン）',
    category: 'content',
    description: 'よくある質問をシンプルにまとめたテンプレート。',
    defaultContent: {
      title: 'よくある質問',
      subtitle: '導入前によくいただく質問をまとめました。',
      items: [
        {
          question: '本当に最短5分でLPを公開できますか？',
          answer: 'AIヒアリングに回答すると構成とコピーが自動生成され、そのまま公開まで行えます。ドメイン設定や決済もワンクリックで完了します。',
        },
        {
          question: '決済や会員サイトは連携できますか？',
          answer: 'Stripe・メール配信・会員サイトへのWebhook連携を標準装備。APIキーを登録するだけで即日稼働できます。',
        },
      ],
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
    } as FAQBlockContent,
  },
  {
    id: 'top-pricing-standard',
    templateId: 'top-pricing-1',
    name: '価格表（ハイライト付き）',
    category: 'conversion',
    description: '2〜3カラムでプラン比較を行えるライトな価格表。',
    defaultContent: {
      title: 'プランと料金',
      subtitle: 'ローンチの規模に合わせて選べる柔軟なプランをご用意しています。',
      plans: [
        {
          name: 'スターター',
          price: '¥29,800',
          period: '/月',
          description: '個人〜小規模チーム向け。月4本までのローンチを高速化。',
          features: ['AIコピー生成', 'テンプレートライブラリ', '公開ホスティング', 'Stripe連携'],
          buttonText: '無料で始める',
        },
        {
          name: 'プロフェッショナル',
          price: '¥79,800',
          period: '/月',
          description: '本格的なローンチ運用に。チームコラボと分析機能を強化。',
          features: ['スタータープランの全機能', 'チーム編集・コメント', 'アクセス分析ダッシュボード', '優先サポート'],
          buttonText: '7日間トライアル',
          highlighted: true,
        },
        {
          name: 'エンタープライズ',
          price: '¥198,000',
          period: '/月',
          description: '年間ローンチ計画と売上管理を専任チームが伴走します。',
          features: ['専属CSチーム', 'Webhookカスタマイズ', 'KPIレポーティング', '広告クリエイティブ制作'],
          buttonText: '相談する',
        },
      ],
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
    } as PricingBlockContent,
  },
  {
    id: 'top-problem-checklist',
    templateId: 'top-problem-1',
    name: '課題提起（チェックリスト）',
    category: 'content',
    description: 'ターゲットの課題をチェックリスト形式で提示するテンプレート。',
    defaultContent: {
      title: 'こんなお悩みはありませんか？',
      subtitle: '情報を届けたいのに、ローンチ準備が複雑すぎると諦めていませんか。',
      problems: [
        '構成やコピーをゼロから考える時間がない',
        'デザイン調整とコーディングで徹夜続き',
        '決済連携や会員エリアの仕組み化が難しい',
        '旬な情報を出したいのに公開までが遅い',
      ],
      backgroundColor: '#FFFFFF',
      textColor: '#0F172A',
    } as ProblemBlockContent,
  },
  {
    id: 'top-before-after-contrast',
    templateId: 'top-before-after-1',
    name: 'ビフォーアフター（コントラスト）',
    category: 'content',
    description: '導入前と導入後の変化を対比で見せるテンプレート。',
    defaultContent: {
      title: '導入前と導入後の変化',
      before: {
        label: 'Before',
        description: '毎回ローンチごとに構成作りとデザインで徹夜。公開までに最低でも2週間はかかっていた。',
      },
      after: {
        label: 'After',
        description: 'AIが構成とコピーを自動生成。チーム3名で週1本のローンチを回せる体制に。',
      },
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
    } as BeforeAfterBlockContent,
  },
  {
    id: 'top-bonus-offer',
    templateId: 'top-bonus-1',
    name: '特典（期間限定オファー）',
    category: 'conversion',
    description: '特典をカード形式で紹介するテンプレート。',
    defaultContent: {
      title: '今だけの参加特典',
      subtitle: '成果までの距離を一気に縮める特典を期間限定でご提供します。',
      totalValue: '合計109,800円相当',
      bonuses: [
        {
          title: '特典1：即実践ローンチテンプレ集',
          description: '成功事例をベースにした構成・コピー例を30種収録。',
          value: '29,800円相当',
        },
        {
          title: '特典2：AIコピー生成クレジット',
          description: '月間300クレジットを無償提供。キャッチコピー量産が可能に。',
          value: '39,800円相当',
        },
      ],
      backgroundColor: '#EBF4FF',
      textColor: '#0F172A',
    } as BonusListBlockContent,
  },
  {
    id: 'top-guarantee-risk-free',
    templateId: 'top-guarantee-1',
    name: '保証（返金保証）',
    category: 'trust',
    description: '返金保証を明確に提示するテンプレート。',
    defaultContent: {
      title: '30日間 全額返金保証',
      subtitle: 'リスクゼロで体験いただくために、安心の保証制度を用意しています。',
      guaranteeDetails: '条件は一切ありません。実際に使ってみてご満足いただけなければ、メール一本で全額返金いたします。',
      badgeText: 'Risk Free',
      bulletPoints: [
        '専任サポートが導入〜初回ローンチまで伴走',
        '再現性の高いAIプロンプトテンプレート付き',
        '返金サポート専用窓口を24時間以内に対応',
      ],
      backgroundColor: '#020617',
      textColor: '#E2E8F0',
    } as GuaranteeBlockContent,
  },
  {
    id: 'top-countdown-urgency',
    templateId: 'top-countdown-1',
    name: 'カウントダウン（緊急オファー）',
    category: 'urgency',
    description: '締切までの残り時間を訴求するカウントダウンテンプレート。',
    defaultContent: {
      title: '特別オファー終了まで',
      urgencyText: '締切までに参加いただいた方限定で、追加特典と返金保証をご提供します。',
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      backgroundColor: '#DC2626',
      textColor: '#FFFFFF',
    } as CountdownBlockContent,
  },
  {
    id: 'top-inline-cta',
    templateId: 'top-inline-cta-1',
    name: 'インラインCTA（カード）',
    category: 'conversion',
    description: 'セクション間に挟み込める軽量CTAテンプレート。',
    defaultContent: {
      eyebrow: '限定プログラム',
      title: '今すぐAIローンチを体験する',
      subtitle: 'アカウント作成から公開までを最短5分で完了。初月の成果創出まで伴走します。',
      buttonText: '無料で始める',
      buttonUrl: '/register',
      backgroundColor: '#FFFFFF',
      textColor: '#0F172A',
    } as InlineCTABlockContent,
  },
];

export const INFO_PRODUCT_BLOCKS: TemplateBlock[] = [];

export const TEMPLATE_CATEGORIES = [
  { id: 'header', name: 'ヒーロー', icon: 'Hero' },
  { id: 'content', name: 'コンテンツ', icon: 'Content' },
  { id: 'conversion', name: 'コンバージョン', icon: 'Conversion' },
  { id: 'trust', name: '信頼・実績', icon: 'Trust' },
  { id: 'urgency', name: '緊急性', icon: 'Urgency' },
];

export function getTemplatesByCategory(category: string) {
  const allTemplates = [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS];
  return allTemplates.filter((template) => template.category === category);
}

export function getTemplateById(templateId: string) {
  const allTemplates = [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS];
  return allTemplates.find((template) => template.templateId === templateId);
}

export function getAllTemplates() {
  return [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS];
}
