import {
  TemplateBlock,
  HeroBlockContent,
  FeaturesBlockContent,
  StickyCTABlockContent,
  TestimonialBlockContent,
  FAQBlockContent,
  CTABlockContent,
  PricingBlockContent,
  ImageBlockContent,
  TemplateThemeKey,
  CountdownBlockContent,
  ProblemBlockContent,
  BeforeAfterBlockContent,
  SpecialPriceBlockContent,
  BonusListBlockContent,
  GuaranteeBlockContent,
  AuthorProfileBlockContent,
  ScarcityBlockContent,
} from "@/types/templates";

const THEME_KEYS: TemplateThemeKey[] = [
  "urgent_red",
  "energy_orange",
  "gold_premium",
  "power_blue",
  "passion_pink",
];

export type ColorThemeKey = TemplateThemeKey;

interface ThemeDefinition {
  primary: string;
  secondary?: string;
  accent: string;
  background: string;
  text: string;
  name: string;
  description: string;
}

export const COLOR_THEMES: Record<ColorThemeKey, ThemeDefinition> = {
  urgent_red: {
    primary: "#DC2626",
    secondary: "#EF4444",
    accent: "#F59E0B",
    background: "#111827",
    text: "#FFFFFF",
    name: "緊急レッド",
    description: "投資・FX・副業に最適",
  },
  energy_orange: {
    primary: "#EA580C",
    secondary: "#F59E0B",
    accent: "#FBBF24",
    background: "#1F2937",
    text: "#FFFFFF",
    name: "エネルギーオレンジ",
    description: "ダイエット・筋トレに最適",
  },
  gold_premium: {
    primary: "#B45309",
    secondary: "#F59E0B",
    accent: "#FCD34D",
    background: "#0F172A",
    text: "#FFFFFF",
    name: "ゴールドプレミアム",
    description: "高額商品・コンサルに最適",
  },
  power_blue: {
    primary: "#1E40AF",
    secondary: "#3B82F6",
    accent: "#60A5FA",
    background: "#111827",
    text: "#FFFFFF",
    name: "パワーブルー",
    description: "学習・資格取得に最適",
  },
  passion_pink: {
    primary: "#BE185D",
    secondary: "#EC4899",
    accent: "#F472B6",
    background: "#1F2937",
    text: "#FFFFFF",
    name: "パッションピンク",
    description: "恋愛・美容に最適",
  },
};

export const TEMPLATE_LIBRARY: TemplateBlock[] = [];

export const INFO_PRODUCT_BLOCKS: TemplateBlock[] = [
  {
    id: "hero-aurora-1",
    templateId: "hero-aurora",
    name: "オーロラヒーロー（ブルー）",
    category: "header",
    description: "学習・副業系に最適な冷静で信頼感のあるヒーローセクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      buttonColor: "#6366F1",
      tagline: "NEXT WAVE",
      title: "AIが導く、24時間で完成するローンチ体験",
      subtitle: "ブランドとコンバージョンを両立するハイエンドLPを、AIワークフローで最短1日で公開。UI設計からコピーまで自動化。",
      highlightText: "AI LAUNCH ACCELERATOR",
      buttonText: "無料で試してみる",
      buttonUrl: "/register",
      secondaryButtonText: "デモを見る",
      secondaryButtonUrl: "/demo",
      imageUrl: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=960&q=80",
      stats: [
        { value: "12h", label: "初稿生成" },
        { value: "87%", label: "CVR改善率" },
        { value: "200+", label: "導入ブランド" },
      ],
    } as HeroBlockContent,
  },
  {
    id: "hero-aurora-2",
    templateId: "hero-aurora",
    name: "オーロラヒーロー（ピンク）",
    category: "header",
    description: "恋愛・美容コンテンツに特化したエモーショナルなヒーロー",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      buttonColor: "#F43F5E",
      tagline: "HEART DATA",
      title: "感情データ×AIで、距離を縮める",
      subtitle: "恋愛・マッチング市場に特化したメッセージ自動化システム。LINE配信からシナリオ最適化まで一気通貫で支援。",
      highlightText: "EMOTIONAL ENGINE",
      buttonText: "90秒デモを見る",
      buttonUrl: "/demo",
      secondaryButtonText: "導入事例資料",
      secondaryButtonUrl: "/case-study",
      imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
      stats: [
        { value: "6.2x", label: "反応率改善" },
        { value: "45日", label: "継続課金率" },
        { value: "92%", label: "LINE移行率" },
      ],
    } as HeroBlockContent,
  },
  {
    id: "hero-aurora-3",
    templateId: "hero-aurora",
    name: "オーロラヒーロー（ゴールド）",
    category: "header",
    description: "高単価・ラグジュアリー系プロダクト向けの重厚なヒーロー",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FEF3C7",
      accentColor: "#FCD34D",
      buttonColor: "#F59E0B",
      tagline: "PREMIUM LAUNCH",
      title: "高額講座のローンチを、データで精密に",
      subtitle: "2,000万円超のローンチを8回成功に導いたプレミアムフレームワーク。受講動線の最適化、FP管理、離脱防止まで網羅。",
      highlightText: "EXECUTIVE PLAYBOOK",
      buttonText: "コンサルティング予約",
      buttonUrl: "/consulting",
      secondaryButtonText: "成果レポートを見る",
      secondaryButtonUrl: "/results",
      imageUrl: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=960&q=80",
      stats: [
        { value: "¥48M", label: "累計売上" },
        { value: "210%", label: "LTV向上" },
        { value: "38名", label: "コンサル顧客" },
      ],
    } as HeroBlockContent,
  },
  {
    id: "hero-aurora-4",
    templateId: "hero-aurora",
    name: "オーロラヒーロー（オレンジ）",
    category: "header",
    description: "ダイエット・フィットネス系のアクティブなヒーロー",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      accentColor: "#F97316",
      buttonColor: "#EA580C",
      tagline: "BODY HACK",
      title: "科学的アプローチで、最短60日シェイプ",
      subtitle: "管理栄養士×AIコーチングが毎日のトレーニングを最適化。習慣化と食事管理をダブルでサポートします。",
      highlightText: "METABOLIC SCIENCE",
      buttonText: "無料カウンセリング",
      buttonUrl: "/trial",
      secondaryButtonText: "成功者インタビュー",
      secondaryButtonUrl: "/voices",
      imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=960&q=80",
      stats: [
        { value: "-7.6kg", label: "平均減量" },
        { value: "93%", label: "継続率" },
        { value: "14日", label: "習慣化サイクル" },
      ],
    } as HeroBlockContent,
  },
  {
    id: "features-aurora-1",
    templateId: "features-aurora",
    name: "機能ハイライト（ブルー）",
    category: "content",
    description: "SaaS・学習系に最適な信頼感のある特徴セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0F172A",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      tagline: "VALUE STACK",
      title: "AI自動化とプロのクリエイティブで、ローンチを最短化",
      highlightText: "KEY FEATURES",
      features: [
        { icon: "⚡️", title: "AI Strategy Engine", description: "ハイコンバージョン構成とコピーをAIが瞬時に生成。訴求軸に合わせた最適なブロックを自動提案。" },
        { icon: "Theme", title: "Premium Theme Library", description: "最新トレンドのテンプレートを即利用。ブランドカラーやタイポグラフィもワンクリックで反映。" },
        { icon: "Analytics", title: "Launch Analytics", description: "ヒートマップやコンバージョン動線を自動分析。改善提案をAIがレコメンド。" },
        { icon: "Team", title: "Collaborative Workflow", description: "チームメンバーとリアルタイム編集。承認フローやコメント機能で制作プロセスを効率化。" },
      ],
    } as FeaturesBlockContent,
  },
  {
    id: "features-aurora-2",
    templateId: "features-aurora",
    name: "機能ハイライト（ピンク）",
    category: "content",
    description: "感情訴求を重視した柔らかいトーンの特徴セクション",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FBCFE8",
      accentColor: "#F472B6",
      tagline: "EMOTIONAL BENEFITS",
      title: "恋愛・美容顧客の共感を生む4つの仕掛け",
      highlightText: "CUSTOMER LOVE",
      features: [
        { icon: "Message", title: "感情テンプレ", description: "10種類の恋愛心理テンプレートから最適なメッセージを自動提案。" },
        { icon: "Insight", title: "顧客インサイトAI", description: "チャット履歴を解析し、刺さる訴求パターンと禁止ワードを自動で提示。" },
        { icon: "Automation", title: "LINE自動分岐", description: "開封・反応データから最適なシナリオに自動分岐。ワンクリックで改善サイクル。" },
        { icon: "Score", title: "感情スコア", description: "共感・信頼・行動意欲をスコアリングし、最適なCTAタイミングを可視化。" },
      ],
    } as FeaturesBlockContent,
  },
  {
    id: "features-aurora-3",
    templateId: "features-aurora",
    name: "機能ハイライト（ゴールド）",
    category: "content",
    description: "プレミアム講座・投資商材向けの重厚な特徴セクション",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      tagline: "WHY IT WORKS",
      title: "高単価ローンチを成功に導く4つの仕組み",
      highlightText: "EXECUTIVE STACK",
      features: [
        { icon: "Diagnostic", title: "プレローンチ診断", description: "過去の成約データを学習したAIが、提供価値と顧客課題のずれを指摘。" },
        { icon: "Pricing", title: "価格最適化モデル", description: "希望売上と目標人数から最適な価格設計と特典シナリオを算出。" },
        { icon: "Dashboard", title: "ライブ改善ダッシュボード", description: "ウェビナー参加率・滞在時間・チャット温度をリアルタイム分析。" },
        { icon: "Community", title: "VIPコミュニティ運用", description: "高単価顧客の継続率を高めるオンボーディングとフォロー導線を生成。" },
      ],
    } as FeaturesBlockContent,
  },
  {
    id: "features-aurora-4",
    templateId: "features-aurora",
    name: "機能ハイライト（オレンジ）",
    category: "content",
    description: "フィットネス・健康習慣訴求に合わせたエネルギッシュな特徴",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1F1206",
      textColor: "#FFEDD5",
      accentColor: "#F97316",
      tagline: "PROGRAM DESIGN",
      title: "習慣化と成果を両立する4つのサイクル",
      highlightText: "BODY TRANSFORMATION",
      features: [
        { icon: "Nutrition", title: "個別栄養ハック", description: "血糖値と活動量から食事サイクルを自動アジャスト。" },
        { icon: "Mind", title: "メンタルトラッキング", description: "朝晩の気分ログを解析し、挫折リスクを事前検知。" },
        { icon: "Roadmap", title: "60日ロードマップ", description: "成果が出やすい順番でトレーニングと休息を設計。" },
        { icon: "Notify", title: "行動通知AI", description: "最適なタイミングでリマインドを送信し、継続率を最大化。" },
      ],
    } as FeaturesBlockContent,
  },
  {
    id: "testimonial-aurora-1",
    templateId: "testimonial-1",
    name: "導入事例（ブルー）",
    category: "social-proof",
    description: "3カラムで権威性と安心感を訴求する導入事例セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      testimonials: [
        { name: "株式会社NovaWorks / 代表取締役", role: "年商3億円案件", text: "LP制作をAI化したことで、制作期間が1/3・CVRが1.8倍に。社内リソースをコア業務に集中できるようになりました。", rating: 5 },
        { name: "FXコミュニティ運営 / 佐藤様", role: "会員数1,200名", text: "ローンチのたびに夜通しで準備していた過去には戻れません。構成・コピー・デザインが一気通貫で仕上がります。", rating: 5 },
        { name: "英語学習アプリ / PM", role: "DL数28万件", text: "ABテストを回す速度が圧倒的に向上。AIが出した仮説を元に改善するだけで初回課金率が26%向上しました。", rating: 5 },
      ],
      layout: "card",
    } as TestimonialBlockContent,
  },
  {
    id: "faq-aurora-1",
    templateId: "faq-1",
    name: "よくある質問（ブルー）",
    category: "content",
    description: "導入前の不安を払拭するアコーディオン型FAQ",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0F172A",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      title: "よくあるご質問",
      faqs: [
        { question: "本当に1日でLPを公開できますか？", answer: "AIヒアリングに回答すると、約30分で初稿が生成されます。1クリックでデプロイまで行えるため、最短24時間で公開可能です。" },
        { question: "デザインを自社のブランドカラーに合わせられますか？", answer: "カラーテーマを選択するだけで全ブロックに反映されます。固有のブランドカラーも3色まで設定可能です。" },
        { question: "既存のCRMや決済システムと連携できますか？", answer: "WebhookとZapier連携を標準搭載。Shopify・Stripe・Pardotなど主要ツールとの連携テンプレートも提供しています。" },
      ],
      layout: "accordion",
    } as FAQBlockContent,
  },
  {
    id: "pricing-aurora-1",
    templateId: "pricing-1",
    name: "価格プラン（ゴールド）",
    category: "conversion",
    description: "高単価商品向けの3カラム価格表。特典と保証を明確に訴求",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      plans: [
        {
          name: "ライトプラン",
          price: "¥98,000",
          period: "分割可",
          description: "個別チャットサポート30日 / 週次グループ講義",
          features: ["ローンチ設計テンプレート", "AIコピー10本", "チェックリスト付き"],
          buttonText: "今すぐ申し込む",
        },
        {
          name: "プレミアム",
          price: "¥298,000",
          period: "人気",
          description: "専属コンサル60日伴走 / フルAI構成 / 成果保証",
          features: ["パーソナル戦略会議", "CVR最適化AI", "ウェビナー台本付き"],
          buttonText: "プレミアムで申し込む",
          highlighted: true,
        },
        {
          name: "エグゼクティブ",
          price: "¥680,000",
          period: "限定10社",
          description: "実装チーム派遣 / 広告運用設計 / 収益最大化",
          features: ["ローンチ全工程代行", "広告クリエイティブ制作", "売上シェア型も可"],
          buttonText: "相談する",
        },
      ],
      columns: 3,
    } as PricingBlockContent,
  },
  {
    id: "cta-aurora-1",
    templateId: "cta-1",
    name: "フル幅CTA（レッド）",
    category: "conversion",
    description: "緊急性と行動喚起を高めるリッチCTAセクション",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      accentColor: "#F97316",
      title: "今すぐローンチをスタートしませんか？",
      subtitle: "無料トライアル30日 + CV改善レポートを今だけ進呈しています。",
      buttonText: "無料アカウントを作成",
      buttonUrl: "/register",
      buttonColor: "#DC2626",
      secondaryButtonText: "導入相談を予約",
      secondaryButtonUrl: "/contact",
    } as CTABlockContent,
  },
  {
    id: "sticky-cta-aurora-1",
    templateId: "sticky-cta-1",
    name: "フローティングCTA（ブルー）",
    category: "conversion",
    description: "視認性の高いフローティングCTAバー",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#050814",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      buttonText: "今すぐAIローンチを始める",
      buttonColor: "#6366F1",
      subText: "⚡ 24時間で初稿生成 / 87%がCVR向上を実感",
      position: "bottom",
    } as StickyCTABlockContent,
  },
  {
    id: "sticky-cta-aurora-2",
    templateId: "sticky-cta-1",
    name: "フローティングCTA（ピンク）",
    category: "conversion",
    description: "恋愛・美容系LPにマッチする華やかなCTAバー",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      buttonText: "限定キャンペーンに参加",
      buttonColor: "#F43F5E",
      subText: "今だけ初月0円 / 残席3名",
      position: "bottom",
    } as StickyCTABlockContent,
  },
  {
    id: "image-aurora-1",
    templateId: "image-1",
    name: "ビジュアルギャラリー（ダーク）",
    category: "image",
    description: "AI生成結果に任意のキービジュアルを差し込めるフル幅イメージブロック",
    defaultContent: {
      backgroundColor: "#050814",
      textColor: "#E2E8F0",
      shadow: true,
      padding: "48px 24px",
      maxWidth: "960px",
      borderRadius: "28px",
      caption: "ビジュアルに合わせてキャプションを編集できます",
      imageUrl: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1280&q=80",
    } as ImageBlockContent,
  },
  // Countdown blocks (5 themes)
  {
    id: "countdown-urgent-red",
    templateId: "countdown-1",
    name: "カウントダウン（緊急レッド）",
    category: "info-product",
    description: "投資・FX・副業向けの緊急性を強調するカウントダウンタイマー",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      title: "⏰ 申込締切まで残りわずか！",
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      urgencyText: "今すぐ申し込まないと、この価格では二度と手に入りません",
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: false,
    } as CountdownBlockContent,
  },
  {
    id: "countdown-energy-orange",
    templateId: "countdown-1",
    name: "カウントダウン（エネルギーオレンジ）",
    category: "info-product",
    description: "ダイエット・筋トレ向けのアクティブなカウントダウン",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      title: "🔥 キャンペーン終了まであとわずか！",
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      urgencyText: "本気で変わりたいあなたへ。今すぐ一歩を踏み出してください",
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: false,
    } as CountdownBlockContent,
  },
  {
    id: "countdown-gold-premium",
    templateId: "countdown-1",
    name: "カウントダウン（ゴールドプレミアム）",
    category: "info-product",
    description: "高額商品向けの重厚感あるカウントダウン",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      title: "⏳ プレミアムオファー終了まで",
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      urgencyText: "限定10名様のみ。このチャンスを逃すと次回募集は半年後です",
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: false,
    } as CountdownBlockContent,
  },
  {
    id: "countdown-power-blue",
    templateId: "countdown-1",
    name: "カウントダウン（パワーブルー）",
    category: "info-product",
    description: "学習・資格取得向けの落ち着いたカウントダウン",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      title: "⏰ 早期申込特典終了まで",
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      urgencyText: "先着30名様限定の特別価格。お早めにお申し込みください",
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: false,
    } as CountdownBlockContent,
  },
  {
    id: "countdown-passion-pink",
    templateId: "countdown-1",
    name: "カウントダウン（パッションピンク）",
    category: "info-product",
    description: "恋愛・美容向けのエモーショナルなカウントダウン",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      title: "💕 特別キャンペーン終了まで",
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      urgencyText: "あなたの理想の未来まで、あと一歩。今すぐ行動しましょう",
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: false,
    } as CountdownBlockContent,
  },
  // Problem blocks (5 themes)
  {
    id: "problem-urgent-red",
    templateId: "problem-1",
    name: "問題提起（緊急レッド）",
    category: "info-product",
    description: "投資・FX・副業向けの課題提起セクション",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      accentColor: "#F97316",
      title: "こんなお悩みはありませんか？",
      subtitle: "多くの方が直面している現実",
      problems: [
        "情報が多すぎて何から手を付ければ良いか分からない",
        "独学では再現性が低く、成果が安定しない",
        "時間も広告費も投入したのに売上が伸び悩んでいる",
        "魅力的なコピーを書けず申し込みにつながらない",
        "ローンチのたびに徹夜続きで疲弊してしまう",
      ],
    } as ProblemBlockContent,
  },
  {
    id: "problem-energy-orange",
    templateId: "problem-1",
    name: "問題提起（エネルギーオレンジ）",
    category: "info-product",
    description: "ダイエット・筋トレ向けの課題提起セクション",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      accentColor: "#F97316",
      title: "こんな悩みを抱えていませんか？",
      subtitle: "多くの方が諦めてしまう理由",
      problems: [
        "何度もダイエットに挑戦したけど、毎回リバウンドしてしまう",
        "忙しくてジムに通う時間がなく、運動が続かない",
        "食事制限が辛くて、いつも途中で挫折してしまう",
        "正しいトレーニング方法が分からず、効果が出ない",
        "モチベーションが続かず、3日坊主で終わってしまう",
      ],
    } as ProblemBlockContent,
  },
  {
    id: "problem-gold-premium",
    templateId: "problem-1",
    name: "問題提起（ゴールドプレミアム）",
    category: "info-product",
    description: "高額商品向けの課題提起セクション",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      title: "経営者が直面する課題",
      subtitle: "成功への道のりを阻む壁",
      problems: [
        "売上は上がったが、利益率が低く手元にお金が残らない",
        "優秀な人材が定着せず、採用と育成に膨大なコストがかかる",
        "競合が増え、価格競争に巻き込まれて疲弊している",
        "マーケティング投資の費用対効果が見えず、判断に迷う",
        "事業を拡大したいが、仕組み化ができず自分の時間が奪われる",
      ],
    } as ProblemBlockContent,
  },
  {
    id: "problem-power-blue",
    templateId: "problem-1",
    name: "問題提起（パワーブルー）",
    category: "info-product",
    description: "学習・資格取得向けの課題提起セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      title: "学習でこんな壁にぶつかっていませんか？",
      subtitle: "独学の限界と課題",
      problems: [
        "参考書を買っても、どこから始めれば良いか分からない",
        "勉強時間を確保しているのに、なかなか成果が出ない",
        "分からないことがあっても、誰にも質問できず前に進めない",
        "モチベーションが続かず、途中で挫折してしまう",
        "試験日が近づいているのに、合格できる自信がない",
      ],
    } as ProblemBlockContent,
  },
  {
    id: "problem-passion-pink",
    templateId: "problem-1",
    name: "問題提起（パッションピンク）",
    category: "info-product",
    description: "恋愛・美容向けの課題提起セクション",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      title: "こんな悩みを抱えていませんか？",
      subtitle: "多くの女性が感じている不安",
      problems: [
        "自分に自信が持てず、恋愛に積極的になれない",
        "外見にコンプレックスがあり、人前に出るのが怖い",
        "何をしても変われない気がして、諦めかけている",
        "周りの目が気になって、本当の自分を出せない",
        "理想の自分に近づきたいけど、何から始めれば良いか分からない",
      ],
    } as ProblemBlockContent,
  },
  // Before-After blocks (5 themes)
  {
    id: "before-after-urgent-red",
    templateId: "before-after-1",
    name: "ビフォーアフター（緊急レッド）",
    category: "info-product",
    description: "投資・FX・副業向けの変化訴求セクション",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      accentColor: "#F97316",
      title: "導入前と導入後の変化",
      beforeTitle: "導入前",
      beforeText: "時間も労力も投資したのに成果が出ない状態。何をやっても売上が伸びず、焦りばかりが募る日々...",
      afterTitle: "導入後",
      afterText: "売上と時間の両立が実現。安定して月商300万円を達成し、自由な時間も手に入れることができました",
    } as BeforeAfterBlockContent,
  },
  {
    id: "before-after-energy-orange",
    templateId: "before-after-1",
    name: "ビフォーアフター（エネルギーオレンジ）",
    category: "info-product",
    description: "ダイエット・筋トレ向けの変化訴求セクション",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      accentColor: "#F97316",
      title: "あなたの未来はこう変わる",
      beforeTitle: "今のあなた",
      beforeText: "何度もダイエットに失敗し、自分に自信が持てない。鏡を見るたびにため息が出る毎日...",
      afterTitle: "60日後のあなた",
      afterText: "理想の体型を手に入れ、自信に満ちた笑顔で毎日を過ごせるように。周りからも「変わったね」と褒められる日々",
    } as BeforeAfterBlockContent,
  },
  {
    id: "before-after-gold-premium",
    templateId: "before-after-1",
    name: "ビフォーアフター（ゴールドプレミアム）",
    category: "info-product",
    description: "高額商品向けの変化訴求セクション",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      title: "経営の質が劇的に変わります",
      beforeTitle: "Before",
      beforeText: "売上は上がっても利益は薄く、自分の時間がない。経営に追われ、本来やりたいビジョン実現からは遠ざかる一方...",
      afterTitle: "After",
      afterText: "利益率30%超を実現し、経営チームが自走。自分は戦略に集中でき、ビジョン実現に向けて着実に前進できる状態に",
    } as BeforeAfterBlockContent,
  },
  {
    id: "before-after-power-blue",
    templateId: "before-after-1",
    name: "ビフォーアフター（パワーブルー）",
    category: "info-product",
    description: "学習・資格取得向けの変化訴求セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      title: "学習効率が劇的に向上",
      beforeTitle: "独学の限界",
      beforeText: "参考書を読んでも理解できず、勉強時間だけが増えていく。このままでは合格できないという不安...",
      afterTitle: "合格への最短ルート",
      afterText: "プロの指導で効率的に学習。疑問点もすぐ解消でき、確実に合格ラインに到達できる実感と自信を獲得",
    } as BeforeAfterBlockContent,
  },
  {
    id: "before-after-passion-pink",
    templateId: "before-after-1",
    name: "ビフォーアフター（パッションピンク）",
    category: "info-product",
    description: "恋愛・美容向けの変化訴求セクション",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      title: "あなたの輝きを取り戻す",
      beforeTitle: "今の自分",
      beforeText: "鏡を見るのが辛く、自分に自信が持てない。外見のコンプレックスで、恋愛にも積極的になれない...",
      afterTitle: "理想の自分",
      afterText: "内面から輝き、自信に満ちた笑顔に。周りからも「綺麗になったね」と言われ、恋愛にも前向きになれる毎日",
    } as BeforeAfterBlockContent,
  },
  // Special Price blocks (5 themes)
  {
    id: "special-price-urgent-red",
    templateId: "special-price-1",
    name: "特別価格（緊急レッド）",
    category: "info-product",
    description: "投資・FX・副業向けの価格訴求セクション",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      accentColor: "#F97316",
      title: "今だけの特別オファー",
      subtitle: "先着30名様限定で特別価格をご用意しました",
      originalPrice: "298,000円",
      specialPrice: "98,000円",
      discountBadge: "67% OFF",
      buttonText: "今すぐ申し込む",
      features: [
        "個別チャットサポート30日",
        "週次グループ講義",
        "成果保証付き",
        "返金保証30日",
      ],
    } as SpecialPriceBlockContent,
  },
  {
    id: "special-price-energy-orange",
    templateId: "special-price-1",
    name: "特別価格（エネルギーオレンジ）",
    category: "info-product",
    description: "ダイエット・筋トレ向けの価格訴求セクション",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      accentColor: "#F97316",
      title: "キャンペーン特別価格",
      subtitle: "本気で変わりたいあなたを応援します",
      originalPrice: "198,000円",
      specialPrice: "59,800円",
      discountBadge: "70% OFF",
      buttonText: "今すぐ始める",
      features: [
        "60日間パーソナルプログラム",
        "食事管理アプリ無料",
        "毎日のフィードバック",
        "リバウンド防止サポート",
      ],
    } as SpecialPriceBlockContent,
  },
  {
    id: "special-price-gold-premium",
    templateId: "special-price-1",
    name: "特別価格（ゴールドプレミアム）",
    category: "info-product",
    description: "高額商品向けの価格訴求セクション",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      title: "プレミアムプラン",
      subtitle: "限定10社様のみの特別価格",
      originalPrice: "2,980,000円",
      specialPrice: "980,000円",
      discountBadge: "67% OFF",
      buttonText: "相談を予約する",
      features: [
        "専属コンサルタント伴走",
        "実装チーム派遣",
        "広告運用設計",
        "売上保証付き",
      ],
    } as SpecialPriceBlockContent,
  },
  {
    id: "special-price-power-blue",
    templateId: "special-price-1",
    name: "特別価格（パワーブルー）",
    category: "info-product",
    description: "学習・資格取得向けの価格訴求セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      title: "早期申込特別価格",
      subtitle: "合格まで徹底サポート",
      originalPrice: "128,000円",
      specialPrice: "49,800円",
      discountBadge: "61% OFF",
      buttonText: "申し込む",
      features: [
        "合格保証付き",
        "無制限質問対応",
        "模擬試験10回分",
        "学習管理アプリ",
      ],
    } as SpecialPriceBlockContent,
  },
  {
    id: "special-price-passion-pink",
    templateId: "special-price-1",
    name: "特別価格（パッションピンク）",
    category: "info-product",
    description: "恋愛・美容向けの価格訴求セクション",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      title: "特別キャンペーン",
      subtitle: "あなたの輝きを応援します",
      originalPrice: "98,000円",
      specialPrice: "29,800円",
      discountBadge: "70% OFF",
      buttonText: "今すぐ参加する",
      features: [
        "30日間集中プログラム",
        "個別カウンセリング",
        "美容アドバイス",
        "コミュニティ参加",
      ],
    } as SpecialPriceBlockContent,
  },
  // Bonus List blocks (5 themes)
  {
    id: "bonus-list-urgent-red",
    templateId: "bonus-list-1",
    name: "特典リスト（緊急レッド）",
    category: "info-product",
    description: "投資・FX・副業向けの特典訴求セクション",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      accentColor: "#F97316",
      title: "申込者限定の豪華特典",
      subtitle: "即実践できる特典で成果までの距離を一気に縮めます",
      bonuses: [
        {
          title: "特典1: ローンチテンプレート集",
          description: "過去200件の実績から厳選した鉄板構成",
          value: "29,800円相当",
        },
        {
          title: "特典2: AIコピーライティングツール",
          description: "見出しから本文まで瞬時に生成",
          value: "50,000円相当",
        },
        {
          title: "特典3: 個別コンサル30分",
          description: "戦略設計を1対1でサポート",
          value: "30,000円相当",
        },
      ],
      totalValue: "合計109,800円相当",
    } as BonusListBlockContent,
  },
  {
    id: "bonus-list-energy-orange",
    templateId: "bonus-list-1",
    name: "特典リスト（エネルギーオレンジ）",
    category: "info-product",
    description: "ダイエット・筋トレ向けの特典訴求セクション",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      accentColor: "#F97316",
      title: "さらに豪華特典をプレゼント",
      subtitle: "成果を最大化するための特別サポート",
      bonuses: [
        {
          title: "特典1: プロテイン1ヶ月分",
          description: "高品質ホエイプロテイン",
          value: "12,000円相当",
        },
        {
          title: "特典2: トレーニングギア",
          description: "自宅トレーニング用品一式",
          value: "18,000円相当",
        },
        {
          title: "特典3: 栄養管理アプリ",
          description: "AI食事管理ツール1年間無料",
          value: "24,000円相当",
        },
      ],
      totalValue: "合計54,000円相当",
    } as BonusListBlockContent,
  },
  {
    id: "bonus-list-gold-premium",
    templateId: "bonus-list-1",
    name: "特典リスト（ゴールドプレミアム）",
    category: "info-product",
    description: "高額商品向けの特典訴求セクション",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      title: "エグゼクティブ特典",
      subtitle: "成功を加速させるプレミアムサポート",
      bonuses: [
        {
          title: "特典1: 経営戦略レポート",
          description: "業界トップコンサルタントによる分析",
          value: "500,000円相当",
        },
        {
          title: "特典2: VIP懇親会",
          description: "成功経営者との交流機会",
          value: "300,000円相当",
        },
        {
          title: "特典3: 実装チーム紹介",
          description: "信頼できるパートナー企業をご紹介",
          value: "無償紹介",
        },
      ],
      totalValue: "合計800,000円相当",
    } as BonusListBlockContent,
  },
  {
    id: "bonus-list-power-blue",
    templateId: "bonus-list-1",
    name: "特典リスト（パワーブルー）",
    category: "info-product",
    description: "学習・資格取得向けの特典訴求セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      title: "合格応援特典",
      subtitle: "学習をサポートする充実の特典",
      bonuses: [
        {
          title: "特典1: 模擬試験10回分",
          description: "本番形式の実践問題",
          value: "15,000円相当",
        },
        {
          title: "特典2: 暗記カード500枚",
          description: "重要ポイント総まとめ",
          value: "8,000円相当",
        },
        {
          title: "特典3: 合格祝い金",
          description: "合格時に10,000円キャッシュバック",
          value: "10,000円",
        },
      ],
      totalValue: "合計33,000円相当",
    } as BonusListBlockContent,
  },
  {
    id: "bonus-list-passion-pink",
    templateId: "bonus-list-1",
    name: "特典リスト（パッションピンク）",
    category: "info-product",
    description: "恋愛・美容向けの特典訴求セクション",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      title: "美容応援特典",
      subtitle: "あなたの変身をサポートします",
      bonuses: [
        {
          title: "特典1: 美容サプリ1ヶ月分",
          description: "内側から輝くための栄養補給",
          value: "8,000円相当",
        },
        {
          title: "特典2: メイクレッスン",
          description: "プロによる個別メイク指導",
          value: "15,000円相当",
        },
        {
          title: "特典3: スタイリング診断",
          description: "パーソナルカラー・骨格診断",
          value: "12,000円相当",
        },
      ],
      totalValue: "合計35,000円相当",
    } as BonusListBlockContent,
  },
  // Guarantee blocks (5 themes)
  {
    id: "guarantee-urgent-red",
    templateId: "guarantee-1",
    name: "保証（緊急レッド）",
    category: "info-product",
    description: "投資・FX・副業向けの保証訴求セクション",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      accentColor: "#F97316",
      title: "安心の保証制度",
      subtitle: "結果が出るまで伴走するリスクゼロの仕組み",
      guaranteeType: "30日間 全額返金保証",
      description: "条件なしでご満足いただけなければ、申請だけでご返金いたします。あなたのリスクはゼロです。",
      badgeText: "リスクゼロ",
    } as GuaranteeBlockContent,
  },
  {
    id: "guarantee-energy-orange",
    templateId: "guarantee-1",
    name: "保証（エネルギーオレンジ）",
    category: "info-product",
    description: "ダイエット・筋トレ向けの保証訴求セクション",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      accentColor: "#F97316",
      title: "成果保証制度",
      subtitle: "結果が出なければ全額返金",
      guaranteeType: "60日間 成果保証",
      description: "プログラム通りに実践しても効果が出なかった場合、全額返金いたします。私たちは本気であなたの変化をサポートします。",
      badgeText: "成果保証",
    } as GuaranteeBlockContent,
  },
  {
    id: "guarantee-gold-premium",
    templateId: "guarantee-1",
    name: "保証（ゴールドプレミアム）",
    category: "info-product",
    description: "高額商品向けの保証訴求セクション",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      title: "プレミアム保証",
      subtitle: "成果にコミットする究極の保証",
      guaranteeType: "売上保証 + 全額返金保証",
      description: "6ヶ月以内に売上が向上しなかった場合、コンサル費用を全額返金。さらに、実装費用もサポートいたします。",
      badgeText: "売上保証",
    } as GuaranteeBlockContent,
  },
  {
    id: "guarantee-power-blue",
    templateId: "guarantee-1",
    name: "保証（パワーブルー）",
    category: "info-product",
    description: "学習・資格取得向けの保証訴求セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      title: "合格保証制度",
      subtitle: "安心して学習に集中できる環境",
      guaranteeType: "合格するまで無料延長",
      description: "万が一不合格だった場合、次回試験まで追加費用なしでサポートを延長。合格するまで徹底的にサポートします。",
      badgeText: "合格保証",
    } as GuaranteeBlockContent,
  },
  {
    id: "guarantee-passion-pink",
    templateId: "guarantee-1",
    name: "保証（パッションピンク）",
    category: "info-product",
    description: "恋愛・美容向けの保証訴求セクション",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      title: "満足保証",
      subtitle: "変化を実感できなければ全額返金",
      guaranteeType: "30日間 満足保証",
      description: "プログラムにご満足いただけなかった場合、理由を問わず全額返金いたします。あなたの笑顔のために全力でサポートします。",
      badgeText: "満足保証",
    } as GuaranteeBlockContent,
  },
  // Author Profile blocks (5 themes)
  {
    id: "author-profile-urgent-red",
    templateId: "author-profile-1",
    name: "講師プロフィール（緊急レッド）",
    category: "info-product",
    description: "投資・FX・副業向けの権威訴求セクション",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      accentColor: "#F97316",
      name: "山田 太郎",
      title: "マーケティングコンサルタント / 情報商材プロデューサー",
      bio: "15年以上のLP制作実績を持ち、累計3,200社のマーケティング支援を担当。特に情報商材分野では平均CVR2.3倍改善を実現。",
      achievements: [
        "累計3,200社のマーケティング支援",
        "平均CVR 2.3倍改善",
        "大手企業・著名講師のプロジェクトを多数監修",
      ],
      signatureText: "山田太郎",
      imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    } as AuthorProfileBlockContent,
  },
  {
    id: "author-profile-energy-orange",
    templateId: "author-profile-1",
    name: "講師プロフィール（エネルギーオレンジ）",
    category: "info-product",
    description: "ダイエット・筋トレ向けの権威訴求セクション",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      accentColor: "#F97316",
      name: "佐藤 健太",
      title: "パーソナルトレーナー / 管理栄養士",
      bio: "10年以上のトレーニング指導経験を持ち、累計1,500名以上の体づくりをサポート。リバウンド率5%以下の実績を誇る。",
      achievements: [
        "累計1,500名以上の指導実績",
        "リバウンド率5%以下",
        "メディア出演多数・著書3冊",
      ],
      signatureText: "佐藤健太",
      imageUrl: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=300&q=80",
    } as AuthorProfileBlockContent,
  },
  {
    id: "author-profile-gold-premium",
    templateId: "author-profile-1",
    name: "講師プロフィール（ゴールドプレミアム）",
    category: "info-product",
    description: "高額商品向けの権威訴求セクション",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      name: "田中 一郎",
      title: "経営コンサルタント / 事業プロデューサー",
      bio: "20年以上の経営コンサルティング経験を持ち、累計500社以上の業績改善を実現。特に高額商材のローンチ成功率は業界トップクラス。",
      achievements: [
        "累計500社以上のコンサルティング実績",
        "平均売上3.2倍改善",
        "上場企業の顧問も多数務める",
      ],
      signatureText: "田中一郎",
      imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
    } as AuthorProfileBlockContent,
  },
  {
    id: "author-profile-power-blue",
    templateId: "author-profile-1",
    name: "講師プロフィール（パワーブルー）",
    category: "info-product",
    description: "学習・資格取得向けの権威訴求セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      name: "鈴木 美咲",
      title: "資格講師 / 学習コンサルタント",
      bio: "12年間の指導経験で累計2,000名以上の合格をサポート。独自の学習メソッドで合格率85%以上を達成。",
      achievements: [
        "累計2,000名以上の合格実績",
        "合格率85%以上",
        "大手資格学校の講師も歴任",
      ],
      signatureText: "鈴木美咲",
      imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=300&q=80",
    } as AuthorProfileBlockContent,
  },
  {
    id: "author-profile-passion-pink",
    templateId: "author-profile-1",
    name: "講師プロフィール（パッションピンク）",
    category: "info-product",
    description: "恋愛・美容向けの権威訴求セクション",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      name: "高橋 さくら",
      title: "美容コンサルタント / イメージアップアドバイザー",
      bio: "8年間で累計800名以上の女性の自信を取り戻すサポートを実施。内面と外見の両方からアプローチする独自メソッドが好評。",
      achievements: [
        "累計800名以上のサポート実績",
        "満足度97%",
        "雑誌・テレビ出演多数",
      ],
      signatureText: "高橋さくら",
      imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
    } as AuthorProfileBlockContent,
  },
  // Scarcity blocks (5 themes)
  {
    id: "scarcity-urgent-red",
    templateId: "scarcity-1",
    name: "残席表示（緊急レッド）",
    category: "info-product",
    description: "投資・FX・副業向けの限定性訴求セクション",
    defaultContent: {
      themeKey: "urgent_red",
      backgroundColor: "#111116",
      textColor: "#F8FAFC",
      accentColor: "#F97316",
      title: "残席状況のご案内",
      message: "募集枠が埋まり次第、予告なく終了します。今すぐお申し込みください。",
      remainingCount: 3,
      totalCount: 30,
    } as ScarcityBlockContent,
  },
  {
    id: "scarcity-energy-orange",
    templateId: "scarcity-1",
    name: "残席表示（エネルギーオレンジ）",
    category: "info-product",
    description: "ダイエット・筋トレ向けの限定性訴求セクション",
    defaultContent: {
      themeKey: "energy_orange",
      backgroundColor: "#1A1207",
      textColor: "#FFEAD5",
      accentColor: "#F97316",
      title: "募集枠のご案内",
      message: "品質を保つため、少人数制で徹底サポートいたします。",
      remainingCount: 5,
      totalCount: 20,
    } as ScarcityBlockContent,
  },
  {
    id: "scarcity-gold-premium",
    templateId: "scarcity-1",
    name: "残席表示（ゴールドプレミアム）",
    category: "info-product",
    description: "高額商品向けの限定性訴求セクション",
    defaultContent: {
      themeKey: "gold_premium",
      backgroundColor: "#120D03",
      textColor: "#FDE68A",
      accentColor: "#F59E0B",
      title: "限定募集のご案内",
      message: "プレミアムサービスのため、厳選した10社様のみ受付いたします。",
      remainingCount: 2,
      totalCount: 10,
    } as ScarcityBlockContent,
  },
  {
    id: "scarcity-power-blue",
    templateId: "scarcity-1",
    name: "残席表示（パワーブルー）",
    category: "info-product",
    description: "学習・資格取得向けの限定性訴求セクション",
    defaultContent: {
      themeKey: "power_blue",
      backgroundColor: "#0B1120",
      textColor: "#E2E8F0",
      accentColor: "#60A5FA",
      title: "受講生募集状況",
      message: "質の高い指導を提供するため、1クラス30名様限定です。",
      remainingCount: 8,
      totalCount: 30,
    } as ScarcityBlockContent,
  },
  {
    id: "scarcity-passion-pink",
    templateId: "scarcity-1",
    name: "残席表示（パッションピンク）",
    category: "info-product",
    description: "恋愛・美容向けの限定性訴求セクション",
    defaultContent: {
      themeKey: "passion_pink",
      backgroundColor: "#1B0F1B",
      textColor: "#FCE7F3",
      accentColor: "#F472B6",
      title: "募集人数のご案内",
      message: "一人ひとりに寄り添うため、少人数制で丁寧にサポートいたします。",
      remainingCount: 4,
      totalCount: 15,
    } as ScarcityBlockContent,
  },
];

export const TEMPLATE_CATEGORIES = [
{ id: "header", name: "ヒーロー", icon: "Hero" },
{ id: "content", name: "コンテンツ", icon: "Content" },
{ id: "conversion", name: "コンバージョン", icon: "Conversion" },
{ id: "info-product", name: "情報商材特化", icon: "Special" },
];

export function getTemplatesByCategory(category: string) {
  if (category === "info-product") {
    return INFO_PRODUCT_BLOCKS;
  }

  const allTemplates = [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS];
  return allTemplates.filter((template) => template.category === category);
}

export function getTemplateById(templateId: string) {
  const allTemplates = [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS];
  return allTemplates.find((template) => template.templateId === templateId);
}

export function getAllTemplates() {
  return [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS];
}
