import {
  TemplateBlock,
  HeroBlockContent,
  FeaturesBlockContent,
  CTABlockContent,
  TestimonialsBlockContent,
  FAQBlockContent,
  PricingBlockContent,
  BeforeAfterBlockContent,
  ProblemBlockContent,
  BonusListBlockContent,
  GuaranteeBlockContent,
  CountdownBlockContent,
  InlineCTABlockContent,
  MediaSpotlightBlockContent,
  ContactBlockContent,
  TokushoBlockContent,
  NewsletterBlockContent,
  TemplateThemeKey,
} from '@/types/templates';

export type ColorThemeKey = TemplateThemeKey;

interface ThemeDefinition {
  primary: string;
  secondary?: string;
  accent: string;
  background: string;
  text: string;
  name: string;
  description: string;
}

export const COLOR_THEMES: Record<ColorThemeKey, ThemeDefinition> = {
  power_blue: {
    primary: '#1E40AF',
    secondary: '#3B82F6',
    accent: '#60A5FA',
    background: '#111827',
    text: '#FFFFFF',
    name: 'パワーブルー',
    description: '学習・資格取得に最適',
  },
  urgent_red: {
    primary: '#DC2626',
    secondary: '#EF4444',
    accent: '#F59E0B',
    background: '#111827',
    text: '#FFFFFF',
    name: '緊急レッド',
    description: '投資・FX・副業に最適',
  },
  energy_orange: {
    primary: '#EA580C',
    secondary: '#F59E0B',
    accent: '#FBBF24',
    background: '#1F2937',
    text: '#FFFFFF',
    name: 'エネルギーオレンジ',
    description: 'ダイエット・筋トレに最適',
  },
  gold_premium: {
    primary: '#B45309',
    secondary: '#F59E0B',
    accent: '#FCD34D',
    background: '#0F172A',
    text: '#FFFFFF',
    name: 'ゴールドプレミアム',
    description: '高額商品・コンサルに最適',
  },
  passion_pink: {
    primary: '#BE185D',
    secondary: '#EC4899',
    accent: '#F472B6',
    background: '#1F2937',
    text: '#FFFFFF',
    name: 'パッションピンク',
    description: '恋愛・美容に最適',
  },
};

export const TEMPLATE_LIBRARY: TemplateBlock[] = [
  {
    id: 'top-hero-landing',
    templateId: 'top-hero-1',
    name: 'ヒーロー（情報鮮度）',
    category: 'header',
    description: 'TOPページのヒーローセクションを再現した軽量テンプレート',
    defaultContent: {
      title: '情報には鮮度がある。',
      subtitle: 'スワイプ型LP作成プラットフォームで、今すぐ情報商材を販売',
      tagline: 'NEXT LAUNCH',
      highlightText: '５分でLP公開',
      buttonText: '無料で始める',
      buttonUrl: '/register',
      secondaryButtonText: 'ログイン',
      secondaryButtonUrl: '/login',
      backgroundVideoUrl: '/videos/pixta.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#050814',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-book-flip',
    templateId: 'top-hero-1',
    name: 'ヒーロー（知識を書籍で紐解く）',
    category: 'header',
    description: '静かな書斎で本をめくる映像を背景に、研究系・教材系に最適なヒーロー。',
    defaultContent: {
      title: '体系化された知識で、最速の結果を。',
      subtitle: '研究と実践で蓄積したノウハウを、動画とテンプレで余すことなく提供します。',
      tagline: 'KNOWLEDGE LAB',
      highlightText: '実践テンプレ付き',
      buttonText: 'プログラムを試す',
      buttonUrl: '/register',
      secondaryButtonText: '資料を請求',
      secondaryButtonUrl: '/download',
      backgroundVideoUrl: '/videos/hero-book-flip.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#080B13',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-couple',
    templateId: 'top-hero-1',
    name: 'ヒーロー（カップルの未来設計）',
    category: 'header',
    description: '寄り添うカップルの映像で、恋愛・ライフスタイル商材に合うヒーロー。',
    defaultContent: {
      title: '二人の距離を縮める、最新メソッド。',
      subtitle: '心理学とデータを組み合わせたシナリオで、恋愛の悩みを解決へ。',
      tagline: 'RELATION DESIGN',
      highlightText: '90日プログラム',
      buttonText: '無料診断を受ける',
      buttonUrl: '/assessment',
      secondaryButtonText: '導入事例を見る',
      secondaryButtonUrl: '/cases',
      backgroundVideoUrl: '/videos/hero-couple.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#0B0E18',
      accentColor: '#38BDF8',
      buttonColor: '#38BDF8',
      secondaryButtonColor: '#F8FAFC',
      overlayColor: '#0B0E18',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-smartphone',
    templateId: 'top-hero-1',
    name: 'ヒーロー（スマホ操作）',
    category: 'header',
    description: 'スマホ操作の映像で、デジタル教材や自動化ツールを訴求できるヒーロー。',
    defaultContent: {
      title: 'スマホ1台で、自動収益の仕組み化。',
      subtitle: 'テンプレを選ぶだけで、LINE構築・決済・配信まで自動化できます。',
      tagline: 'MOBILE AUTOMATION',
      highlightText: '完全ノーコード',
      buttonText: '無料トライアル',
      buttonUrl: '/register',
      secondaryButtonText: '機能を見る',
      secondaryButtonUrl: '/features',
      backgroundVideoUrl: '/videos/hero-smartphone.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#050811',
      accentColor: '#38BDF8',
      buttonColor: '#38BDF8',
      secondaryButtonColor: '#F8FAFC',
      overlayColor: '#050811',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-night-crossing',
    templateId: 'top-hero-1',
    name: 'ヒーロー（夜の交差点）',
    category: 'header',
    description: '都会の交差点を背景に、スピード感と勢いを演出できるヒーロー。',
    defaultContent: {
      title: '一晩で市場を席巻する、ローンチ戦略。',
      subtitle: '高速な意思決定とAI自動化で、旬な情報を一気に届ける。',
      tagline: 'NIGHT LAUNCH',
      highlightText: 'スピード配信',
      buttonText: 'ローンチを設計する',
      buttonUrl: '/register',
      secondaryButtonText: 'ロードマップを見る',
      secondaryButtonUrl: '/roadmap',
      backgroundVideoUrl: '/videos/hero-night-crossing.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#030611',
      accentColor: '#F97316',
      buttonColor: '#F97316',
      secondaryButtonColor: '#FED7AA',
      overlayColor: '#030611',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-night-road',
    templateId: 'top-hero-1',
    name: 'ヒーロー（夜の道路）',
    category: 'header',
    description: '光が流れる夜の道路映像で、投資・副業系の緊張感を演出。',
    defaultContent: {
      title: '市場の波に乗り遅れない、即断即決の情報セット。',
      subtitle: '最新の相場データを毎朝5時に配信。行動する投資家のための学習プラットフォーム。',
      tagline: 'MARKET SIGNAL',
      highlightText: '毎朝5時配信',
      buttonText: '今すぐ参加する',
      buttonUrl: '/register',
      secondaryButtonText: '説明会を見る',
      secondaryButtonUrl: '/webinar',
      backgroundVideoUrl: '/videos/hero-night-road.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#05070F',
      accentColor: '#FACC15',
      buttonColor: '#FACC15',
      secondaryButtonColor: '#FDE68A',
      overlayColor: '#05070F',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-smoke',
    templateId: 'top-hero-1',
    name: 'ヒーロー（スモーク演出）',
    category: 'header',
    description: '幻想的な煙の映像で、ブランディング性の高い講座訴求に活用。',
    defaultContent: {
      title: '世界観で魅了する、ハイブランド講座。',
      subtitle: '空間演出やストーリーテリングを組み込んだ、プレミアムローンチパッケージ。',
      tagline: 'PREMIUM STAGE',
      highlightText: '世界観設計',
      buttonText: 'コンセプトを体験',
      buttonUrl: '/register',
      secondaryButtonText: '世界観資料を請求',
      secondaryButtonUrl: '/concept-book',
      backgroundVideoUrl: '/videos/hero-smoke.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#070710',
      accentColor: '#C084FC',
      buttonColor: '#C084FC',
      secondaryButtonColor: '#F5F3FF',
      overlayColor: '#070710',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-beach',
    templateId: 'top-hero-1',
    name: 'ヒーロー（砂浜と海）',
    category: 'header',
    description: '穏やかな波の映像で、ライフスタイルやウェルネス訴求に適したヒーロー。',
    defaultContent: {
      title: '理想の暮らしをデザインする、習慣づくりプログラム。',
      subtitle: '時間と場所に縛られない働き方・生き方を、3ヶ月で手に入れる。',
      tagline: 'LIFESTYLE SHIFT',
      highlightText: '60日伴走',
      buttonText: '無料ウェビナーに参加',
      buttonUrl: '/webinar',
      secondaryButtonText: '受講生の体験談',
      secondaryButtonUrl: '/voices',
      backgroundVideoUrl: '/videos/hero-beach.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#061019',
      accentColor: '#34D399',
      buttonColor: '#34D399',
      secondaryButtonColor: '#CCFBF1',
      overlayColor: '#061019',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-downtown',
    templateId: 'top-hero-1',
    name: 'ヒーロー（繁華街の熱量）',
    category: 'header',
    description: '繁華街のネオンと人の流れで、エネルギッシュな市場を印象づけるヒーロー。',
    defaultContent: {
      title: '熱量の高い市場で、一気に認知を獲得する。',
      subtitle: 'SNS広告と連動したローンチ設計で、初動から売上を最大化。',
      tagline: 'URBAN IMPACT',
      highlightText: 'SNSアセット付',
      buttonText: 'プロジェクトを相談',
      buttonUrl: '/contact',
      secondaryButtonText: '戦略資料をダウンロード',
      secondaryButtonUrl: '/strategy',
      backgroundVideoUrl: '/videos/hero-downtown.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#050510',
      accentColor: '#F97316',
      buttonColor: '#F97316',
      secondaryButtonColor: '#FED7AA',
      overlayColor: '#050510',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-tiger',
    templateId: 'top-hero-1',
    name: 'ヒーロー（虎の咆哮）',
    category: 'header',
    description: '虎の迫力ある映像で、自己啓発やマインドセット系に響くヒーロー。',
    defaultContent: {
      title: '内なる野性を解き放ち、圧倒的な成果へ。',
      subtitle: 'メンタルと戦略を同時に鍛えるエリート講座。勝ち続ける思考を48時間でインストール。',
      tagline: 'UNLEASH POWER',
      highlightText: '2Days集中',
      buttonText: '集中合宿に申し込む',
      buttonUrl: '/bootcamp',
      secondaryButtonText: '講師のメッセージ',
      secondaryButtonUrl: '/message',
      backgroundVideoUrl: '/videos/hero-tiger.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#080808',
      accentColor: '#F97316',
      buttonColor: '#F97316',
      secondaryButtonColor: '#FED7AA',
      overlayColor: '#080808',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-running-man',
    templateId: 'top-hero-1',
    name: 'ヒーロー（走る男性）',
    category: 'header',
    description: '走り抜ける男性の映像で、フィットネスや習慣化商材を訴求。',
    defaultContent: {
      title: '60日で体を変える、科学的トレーニング。',
      subtitle: '栄養・運動・メンタルをAIが伴走サポート。挫折ゼロのダイエットプログラム。',
      tagline: 'BODY MAKE',
      highlightText: 'パーソナルAI',
      buttonText: '無料カウンセリング',
      buttonUrl: '/trial',
      secondaryButtonText: '成功者インタビュー',
      secondaryButtonUrl: '/voices',
      backgroundVideoUrl: '/videos/hero-running-man.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#070B10',
      accentColor: '#22C55E',
      buttonColor: '#22C55E',
      secondaryButtonColor: '#BBF7D0',
      overlayColor: '#070B10',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-gold-particles',
    templateId: 'top-hero-1',
    name: 'ヒーロー（金の粒子）',
    category: 'header',
    description: '金色の粒子が舞う映像で、プレミアムな高額商品を演出するヒーロー。',
    defaultContent: {
      title: '価値が伝わる、プレミアムローンチへ。',
      subtitle: '高額講座に特化したフルファネル構築で、単価と成約率を最大化。',
      tagline: 'EXECUTIVE LAUNCH',
      highlightText: 'VIP限定',
      buttonText: '戦略セッションを予約',
      buttonUrl: '/consulting',
      secondaryButtonText: '導入実績を見る',
      secondaryButtonUrl: '/results',
      backgroundVideoUrl: '/videos/hero-gold-particles.mp4',
      textColor: '#FFFFFF',
      backgroundColor: '#0A0603',
      accentColor: '#FACC15',
      buttonColor: '#FACC15',
      secondaryButtonColor: '#FEF08A',
      overlayColor: '#0A0603',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-finance',
    templateId: 'top-hero-1',
    name: 'ヒーロー（金融アドバイザー）',
    category: 'header',
    description: 'スーツ姿の男性が資料を確認する映像で、投資・資産運用の信頼感を演出。',
    defaultContent: {
      title: 'プロの伴走で、資産形成を次のステージへ。',
      subtitle: '市場データとAI分析に基づき、個別最適な投資プランを設計します。',
      tagline: 'FINANCE ADVISOR',
      highlightText: '運用改善率182%',
      buttonText: '無料相談を予約',
      buttonUrl: '/consulting',
      secondaryButtonText: '導入事例',
      secondaryButtonUrl: '/results',
      backgroundVideoUrl: '/videos/hero-finance-man.mp4',
      textColor: '#0F172A',
      backgroundColor: '#E2E8F0',
      accentColor: '#2563EB',
      buttonColor: '#2563EB',
      secondaryButtonColor: '#1E40AF',
      overlayColor: '#0B1120',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-money-rain',
    templateId: 'top-hero-1',
    name: 'ヒーロー（マネーシャワー）',
    category: 'header',
    description: '舞い落ちる紙幣の映像で、キャンペーンや成果訴求の高揚感を演出。',
    defaultContent: {
      title: '限定オファーで、爆発的な売上を。',
      subtitle: 'ローンチスケジュールと広告運用を一元管理し、初動で最大の成果を出します。',
      tagline: 'LIMITED CAMPAIGN',
      highlightText: '成約率2.4倍',
      buttonText: '枠を確保する',
      buttonUrl: '/reserve',
      secondaryButtonText: '成功事例を見る',
      secondaryButtonUrl: '/cases',
      backgroundVideoUrl: '/videos/hero-money-rain.mov',
      textColor: '#1F2937',
      backgroundColor: '#FEF3C7',
      accentColor: '#F59E0B',
      buttonColor: '#F97316',
      secondaryButtonColor: '#B45309',
      overlayColor: '#7C2D12',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-keyboard',
    templateId: 'top-hero-1',
    name: 'ヒーロー（キーボード操作）',
    category: 'header',
    description: 'メカニカルキーボードを打鍵する映像で、SaaSや開発支援のプロフェッショナル感を強調。',
    defaultContent: {
      title: '開発チームの生産性を、2クリックで引き上げる。',
      subtitle: 'ドキュメント自動生成とレビュー支援で、エンジニアリングコストを最適化。',
      tagline: 'CODE ACCELERATOR',
      highlightText: '開発効率170%',
      buttonText: 'プロダクトを試す',
      buttonUrl: '/product',
      secondaryButtonText: '導入の流れ',
      secondaryButtonUrl: '/onboarding',
      backgroundVideoUrl: '/videos/hero-keyboard.mp4',
      textColor: '#F8FAFC',
      backgroundColor: '#0F172A',
      accentColor: '#38BDF8',
      buttonColor: '#38BDF8',
      secondaryButtonColor: '#CBD5F5',
      overlayColor: '#0B1120',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-keyboard-precision',
    templateId: 'top-hero-1',
    name: 'ヒーロー（キーボード・精密作業）',
    category: 'header',
    description: 'キーボードを高速タイピングする手元の映像で、クリエイティブや執筆サービスに最適。',
    defaultContent: {
      title: '言葉とクリエイティブを、秒で量産する。',
      subtitle: 'AIコピーと構成テンプレートで、制作時間を大幅に短縮します。',
      tagline: 'CONTENT STUDIO',
      highlightText: '制作時間1/3',
      buttonText: '無料で体験する',
      buttonUrl: '/trial',
      secondaryButtonText: '機能一覧',
      secondaryButtonUrl: '/features',
      backgroundVideoUrl: '/videos/hero-keyboard-2.mp4',
      textColor: '#F8FAFC',
      backgroundColor: '#111827',
      accentColor: '#8B5CF6',
      buttonColor: '#8B5CF6',
      secondaryButtonColor: '#DDD6FE',
      overlayColor: '#1E1B4B',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-puzzle',
    templateId: 'top-hero-1',
    name: 'ヒーロー（ジグソーパズル）',
    category: 'header',
    description: 'パズルを組み合わせる映像で、戦略立案やコンサルティングの「構造化」を訴求。',
    defaultContent: {
      title: '複雑な戦略を、シンプルなピースに分解する。',
      subtitle: 'ロードマップとKPI設計をテンプレート化し、確実に成果へ導きます。',
      tagline: 'STRATEGY DESIGN',
      highlightText: 'プロジェクト成功率94%',
      buttonText: '戦略相談を申し込む',
      buttonUrl: '/consulting',
      secondaryButtonText: 'プランを見る',
      secondaryButtonUrl: '/pricing',
      backgroundVideoUrl: '/videos/hero-jigsaw-puzzle.mp4',
      textColor: '#0F172A',
      backgroundColor: '#F8FAFC',
      accentColor: '#2563EB',
      buttonColor: '#2563EB',
      secondaryButtonColor: '#1D4ED8',
      overlayColor: '#0B1120',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-clock',
    templateId: 'top-hero-1',
    name: 'ヒーロー（回転する時計）',
    category: 'header',
    description: '回転する壁時計の映像で、時間管理やデッドラインの緊張感を表現。',
    defaultContent: {
      title: '時間を味方に、成果を最大化。',
      subtitle: '自動スケジューラーと通知設計で、チームのタスクを確実に前進させます。',
      tagline: 'TIME MANAGEMENT',
      highlightText: '遅延ゼロ運用',
      buttonText: 'プロダクトを試す',
      buttonUrl: '/product',
      secondaryButtonText: '導入サポート',
      secondaryButtonUrl: '/support',
      backgroundVideoUrl: '/videos/hero-rotating-clock.mp4',
      textColor: '#F8FAFC',
      backgroundColor: '#020617',
      accentColor: '#38BDF8',
      buttonColor: '#38BDF8',
      secondaryButtonColor: '#94A3B8',
      overlayColor: '#0B1120',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-leather-shoes',
    templateId: 'top-hero-1',
    name: 'ヒーロー（革靴のビジネスパーソン）',
    category: 'header',
    description: '颯爽と歩く革靴の映像で、ビジネスエリート向けサービスの躍動感を演出。',
    defaultContent: {
      title: 'プロフェッショナルの伴走で、次の成果を掴む。',
      subtitle: '営業・マーケ・CSを一体化した伴走チームが、組織の成長をブースト。',
      tagline: 'BUSINESS ELITE',
      highlightText: '成果創出90日',
      buttonText: '相談する',
      buttonUrl: '/contact',
      secondaryButtonText: 'プログラム詳細',
      secondaryButtonUrl: '/program',
      backgroundVideoUrl: '/videos/hero-leather-shoes.mp4',
      textColor: '#F8FAFC',
      backgroundColor: '#0F172A',
      accentColor: '#FACC15',
      buttonColor: '#F59E0B',
      secondaryButtonColor: '#FDE68A',
      overlayColor: '#0B1120',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-image-sky',
    templateId: 'top-hero-image-1',
    name: 'ヒーロー（イメージ）',
    category: 'header',
    description: '動画を使わずに背景画像で魅せるフルスクリーンヒーロー。アップロードした画像をそのまま背景に設定できます。',
    defaultContent: {
      title: 'ブランド世界観を崩さず、成果につながる制作を。',
      subtitle: 'ノーコード編集とAI支援で、構成から公開までを5分で完了。',
      tagline: 'CREATIVE LAUNCH',
      highlightText: '撮影不要・即公開',
      buttonText: '無料で始める',
      buttonUrl: '/register',
      secondaryButtonText: '実績を見る',
      secondaryButtonUrl: '/cases',
      backgroundImageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&q=80',
      textColor: '#FFFFFF',
      backgroundColor: '#0B1120',
      overlayColor: '#0B1120',
      accentColor: '#38BDF8',
      buttonColor: '#38BDF8',
      secondaryButtonColor: '#F8FAFC',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-image-mint',
    templateId: 'top-hero-image-1',
    name: 'ヒーロー（イメージ・ミント）',
    category: 'header',
    description: 'ウェルネスやライフスタイル向けの柔らかなミントトーン。背景画像はユーザーが自由に差し替え可能です。',
    defaultContent: {
      title: '心と体を整える、新しい習慣づくりをサポート。',
      subtitle: 'AIコーチとテンプレートを組み合わせた、60日の習慣化プログラム。',
      tagline: 'HABIT DESIGN',
      highlightText: 'セルフケアに最適',
      buttonText: '無料カウンセリング',
      buttonUrl: '/trial',
      secondaryButtonText: '受講生の声',
      secondaryButtonUrl: '/voices',
      backgroundImageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1600&q=80',
      textColor: '#0F172A',
      backgroundColor: '#ECFDF5',
      overlayColor: '#064E3B',
      accentColor: '#10B981',
      buttonColor: '#10B981',
      secondaryButtonColor: '#047857',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-image-amber',
    templateId: 'top-hero-image-1',
    name: 'ヒーロー（イメージ・アンバー）',
    category: 'header',
    description: 'エネルギッシュなアンバーカラーで勢いを演出。サマーキャンペーンや限定オファーに最適。',
    defaultContent: {
      title: '限定オファーで、一気に認知を拡大。',
      subtitle: 'SNS広告・メール・LPを統合した施策で、初動から販売を加速します。',
      tagline: 'LIMITED OFFER',
      highlightText: '期間限定',
      buttonText: '枠を確保する',
      buttonUrl: '/reserve',
      secondaryButtonText: 'プランを見る',
      secondaryButtonUrl: '/pricing',
      backgroundImageUrl: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1600&q=80',
      textColor: '#1F2937',
      backgroundColor: '#FFF7ED',
      overlayColor: '#451A03',
      accentColor: '#F97316',
      buttonColor: '#EA580C',
      secondaryButtonColor: '#78350F',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-image-violet',
    templateId: 'top-hero-image-1',
    name: 'ヒーロー（イメージ・バイオレット）',
    category: 'header',
    description: 'プレミアムな体験を訴求できるバイオレットトーン。高単価講座やブランド商材向け。',
    defaultContent: {
      title: '世界観を磨き上げ、熱量の高いファンを育てる。',
      subtitle: 'ブランドストーリーとデザインを統合し、記憶に残る体験を設計します。',
      tagline: 'PREMIUM EXPERIENCE',
      highlightText: 'ラグジュアリー領域',
      buttonText: 'コンサルを予約',
      buttonUrl: '/consulting',
      secondaryButtonText: '資料を請求',
      secondaryButtonUrl: '/download',
      backgroundImageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1600&q=80',
      textColor: '#FFFFFF',
      backgroundColor: '#312E81',
      overlayColor: '#1E1B4B',
      accentColor: '#A855F7',
      buttonColor: '#8B5CF6',
      secondaryButtonColor: '#DDD6FE',
    } as HeroBlockContent,
  },
  {
    id: 'top-hero-image-slate',
    templateId: 'top-hero-image-1',
    name: 'ヒーロー（イメージ・モノトーン）',
    category: 'header',
    description: '落ち着いたモノトーンでBtoBやプロ向けの信頼感を高める構成。',
    defaultContent: {
      title: 'データと実行力で、事業の成長を支援します。',
      subtitle: '戦略策定から実装・検証まで、専任チームが伴走するBtoB向けソリューション。',
      tagline: 'PRO PARTNERSHIP',
      highlightText: '伴走支援',
      buttonText: '相談する',
      buttonUrl: '/contact',
      secondaryButtonText: '導入事例',
      secondaryButtonUrl: '/cases',
      backgroundImageUrl: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1600&q=80',
      textColor: '#F8FAFC',
      backgroundColor: '#0F172A',
      overlayColor: '#0B1120',
      accentColor: '#94A3B8',
      buttonColor: '#38BDF8',
      secondaryButtonColor: '#CBD5F5',
    } as HeroBlockContent,
  },
  {
    id: 'top-highlights-grid',
    templateId: 'top-highlights-1',
    name: 'ハイライト（課題から提案へ）',
    category: 'content',
    description: '課題と解決策のセットで価値を伝えるハイライトテンプレート。',
    defaultContent: {
      title: 'こんな課題、ありませんか？',
      tagline: 'Pain Points',
      features: [
        {
          icon: '🎨',
          title: 'デザイン設計に時間を奪われる',
          description: 'ゼロから構成やビジュアルを整えるのは非効率で差別化も難しい。',
        },
        {
          icon: '🌐',
          title: 'ドメイン・サーバー整備が面倒',
          description: '取得・SSL対応まで段取りに追われ、初動が遅れる。',
        },
        {
          icon: '💳',
          title: '決済機能の実装ハードル',
          description: '安全な決済フローの準備には高い技術とセキュリティ知識が必要。',
        },
      ],
      backgroundColor: '#F1F5F9',
      textColor: '#0F172A',
      accentColor: '#2563EB',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-highlights-mint',
    templateId: 'top-highlights-1',
    name: 'ハイライト（ミント）',
    category: 'content',
    description: '爽やかなミントトーンで、ウェルネスや自己啓発向けの課題訴求に最適。',
    defaultContent: {
      title: '新しい習慣が続かない理由',
      tagline: 'Lifestyle Shift',
      features: [
        {
          icon: '🌿',
          title: '行動が三日坊主で終わる',
          description: '継続の仕組みがなく、気合と根性に頼ってしまう。',
        },
        {
          icon: '🧘‍♀️',
          title: 'メンタルの切り替えが難しい',
          description: '自分に合ったリズムを知らず、ストレスでリバウンドしてしまう。',
        },
        {
          icon: '📊',
          title: '成果が可視化できない',
          description: '感覚だけで取り組み、伸びている実感が持てずモチベが続かない。',
        },
      ],
      backgroundColor: '#E0F7F4',
      textColor: '#064E3B',
      accentColor: '#0D9488',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-highlights-amber',
    templateId: 'top-highlights-1',
    name: 'ハイライト（アンバー）',
    category: 'content',
    description: '温かみのあるアンバー配色で、ビジネスや教育商材の課題訴求に。',
    defaultContent: {
      title: 'ビジネス成長が頭打ちになる原因',
      tagline: 'Growth Issues',
      features: [
        {
          icon: '📈',
          title: '戦略が属人化している',
          description: 'トッププレイヤーのノウハウが共有されず、再現性が低い。',
        },
        {
          icon: '🧭',
          title: '改善指標が曖昧',
          description: 'KPIの設定が曖昧で、何から手を付けるべきか判断できない。',
        },
        {
          icon: '🤝',
          title: 'チーム連携が機能していない',
          description: '部署間で情報共有ができず、施策のスピードが落ちている。',
        },
      ],
      backgroundColor: '#FFF7ED',
      textColor: '#7C2D12',
      accentColor: '#F97316',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-highlights-violet',
    templateId: 'top-highlights-1',
    name: 'ハイライト（バイオレット）',
    category: 'content',
    description: '落ち着いたバイオレットで、権威性や信頼を訴求する情報商材向け。',
    defaultContent: {
      title: '学びが成果につながらない理由',
      tagline: 'Insight Points',
      features: [
        {
          icon: '🧠',
          title: '情報が頭でっかちになる',
          description: 'インプット偏重で、実践に落とし込むフレームがない。',
        },
        {
          icon: '🪜',
          title: '段階設計が不十分',
          description: '初級〜上級の橋渡しがなく、途中で挫折してしまう。',
        },
        {
          icon: '🔍',
          title: '本質的な課題が見えていない',
          description: '現状分析が甘く、施策が的外れになってしまう。',
        },
      ],
      backgroundColor: '#F3E8FF',
      textColor: '#2E1065',
      accentColor: '#8B5CF6',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-highlights-slate',
    templateId: 'top-highlights-1',
    name: 'ハイライト（モノトーン）',
    category: 'content',
    description: 'シックなモノトーンで、汎用性の高いビジネスシーン向け課題訴求。',
    defaultContent: {
      title: 'プロジェクトが停滞する兆候',
      tagline: 'Project Risks',
      features: [
        {
          icon: '🕒',
          title: '意思決定が遅い',
          description: '判断基準が不明瞭で、会議だけが増えてしまう。',
        },
        {
          icon: '🧾',
          title: 'タスクが散らばっている',
          description: '情報が複数のツールに散在し、全体最適ができていない。',
        },
        {
          icon: '🧩',
          title: '責任領域が曖昧',
          description: '誰が何をやるのか定義されず、成果が属人化している。',
        },
      ],
      backgroundColor: '#F8FAFC',
      textColor: '#111827',
      accentColor: '#475569',
    } as FeaturesBlockContent,
  },
  {
    id: 'top-cta-gradient',
    templateId: 'top-cta-1',
    name: 'CTA（スカイグラデーション）',
    category: 'conversion',
    description: '深いブルーグラデーションで緊張感と信頼感を両立したCTA。',
    defaultContent: {
      eyebrow: 'Launch Ready',
      title: '今すぐ始めよう',
      subtitle: '情報には鮮度がある。５分でLPを公開して、今すぐ販売を開始。',
      buttonText: '無料で始める',
      buttonUrl: '/register',
      secondaryButtonText: 'デモを見る',
      secondaryButtonUrl: '/demo',
      backgroundColor: '#07182F',
      backgroundGradient: 'linear-gradient(135deg, rgba(56,189,248,0.28), rgba(14,116,144,0.28))',
      surfaceColor: '#10233F',
      textColor: '#ECFEFF',
      accentColor: '#38BDF8',
      buttonColor: '#38BDF8',
      secondaryButtonColor: '#38BDF8',
    } as CTABlockContent,
  },
  {
    id: 'top-cta-lavender',
    templateId: 'top-cta-1',
    name: 'CTA（ラベンダー）',
    category: 'conversion',
    description: 'ラベンダートーンで洗練された世界観を演出するCTA。',
    defaultContent: {
      eyebrow: 'Premium Access',
      title: 'ブランド体験を、次のステージへ。',
      subtitle: 'ハイタッチな顧客体験を実現するオートメーションワークフローを、24時間以内に構築。',
      buttonText: 'コンサルを予約する',
      buttonUrl: '/consulting',
      secondaryButtonText: '導入事例を見る',
      secondaryButtonUrl: '/case-study',
      backgroundColor: '#322C81',
      backgroundGradient: 'linear-gradient(135deg, rgba(192,132,252,0.32), rgba(79,70,229,0.32))',
      surfaceColor: '#3F3C99',
      textColor: '#F5F3FF',
      accentColor: '#C084FC',
      buttonColor: '#C084FC',
      secondaryButtonColor: '#F5F3FF',
    } as CTABlockContent,
  },
  {
    id: 'top-cta-emerald',
    templateId: 'top-cta-1',
    name: 'CTA（エメラルド）',
    category: 'conversion',
    description: '自然なエネルギーを感じさせるエメラルド配色のCTA。',
    defaultContent: {
      eyebrow: 'Habit Design',
      title: '60日間で、習慣と成果をデザインする。',
      subtitle: 'AIトレーナーが日々の行動をチューニング。リバウンドしない仕組みを伴走で構築します。',
      buttonText: '無料カウンセリング',
      buttonUrl: '/trial',
      secondaryButtonText: 'プログラム内容を見る',
      secondaryButtonUrl: '/program',
      backgroundColor: '#064E3B',
      backgroundGradient: 'linear-gradient(135deg, rgba(52,211,153,0.32), rgba(13,148,136,0.32))',
      surfaceColor: '#0B5C43',
      textColor: '#ECFDF5',
      accentColor: '#34D399',
      buttonColor: '#34D399',
      secondaryButtonColor: '#A7F3D0',
    } as CTABlockContent,
  },
  {
    id: 'top-cta-amber',
    templateId: 'top-cta-1',
    name: 'CTA（アンバー）',
    category: 'conversion',
    description: '熱量と緊張感を演出するアンバーグラデーションのCTA。',
    defaultContent: {
      eyebrow: 'Limited Offer',
      title: '先着限定の特別枠にご招待。',
      subtitle: '成約率を最大化するローンチ構築を、専任チームが30日で伴走実装。',
      buttonText: '枠を確保する',
      buttonUrl: '/reserve',
      secondaryButtonText: 'プランを比較する',
      secondaryButtonUrl: '/pricing',
      backgroundColor: '#431407',
      backgroundGradient: 'linear-gradient(135deg, rgba(249,115,22,0.35), rgba(217,119,6,0.35))',
      surfaceColor: '#5C1E0A',
      textColor: '#FFF7ED',
      accentColor: '#F97316',
      buttonColor: '#F97316',
      secondaryButtonColor: '#FED7AA',
    } as CTABlockContent,
  },
  {
    id: 'top-cta-slate',
    templateId: 'top-cta-1',
    name: 'CTA（モノトーン）',
    category: 'conversion',
    description: 'モノトーンとブルーグレーで汎用性の高いCTA。',
    defaultContent: {
      eyebrow: 'Join the Network',
      title: 'コミュニティで、事業を加速させよう。',
      subtitle: '最新事例とテンプレートを共有するオンラインコミュニティに参加し、改善サイクルを回しましょう。',
      buttonText: 'コミュニティに参加',
      buttonUrl: '/community',
      secondaryButtonText: '資料をダウンロード',
      secondaryButtonUrl: '/download',
      backgroundColor: '#111827',
      backgroundGradient: 'linear-gradient(135deg, rgba(148,163,184,0.28), rgba(15,23,42,0.28))',
      surfaceColor: '#1E293B',
      textColor: '#F8FAFC',
      accentColor: '#94A3B8',
      buttonColor: '#F1F5F9',
      secondaryButtonColor: '#94A3B8',
    } as CTABlockContent,
  },
  {
    id: 'top-testimonials-sky',
    templateId: 'top-testimonials-1',
    name: 'お客様の声（スカイ）',
    category: 'trust',
    description: 'ブルートーンで爽やかな信頼感を演出する2カラムレイアウト。',
    defaultContent: {
      title: 'お客様の声',
      subtitle: '導入企業や受講生のリアルな成果をご紹介します。',
      testimonials: [
        {
          quote: 'AIがコピー案を提案してくれるので、初稿制作が一気に楽になりました。初月から前年度比180%の売上です。',
          name: 'オンライン講座運営 / 佐藤様',
          role: '年間売上1.2億円',
        },
        {
          quote: 'ランディングページ制作の外注費を70%削減。自社メンバーだけで週1ペースのローンチが回せています。',
          name: 'マーケティング会社 / 山田様',
          role: 'チーム3名で運用',
        },
      ],
      backgroundColor: '#FFFFFF',
      textColor: '#0F172A',
      accentColor: '#2563EB',
    } as TestimonialsBlockContent,
  },
  {
    id: 'top-testimonials-mint',
    templateId: 'top-testimonials-1',
    name: 'お客様の声（ミント）',
    category: 'trust',
    description: '柔らかなミントグリーンで親しみやすさと安心感を両立。',
    defaultContent: {
      title: 'お客様の声',
      subtitle: '導入後に成果が出たリアルな声をご紹介します。',
      testimonials: [
        {
          quote: 'UIがシンプルで導入初日から営業資料が完成。商談化率が27%向上しました。',
          name: 'BtoBスタートアップ / 田中様',
          role: 'フィールドセールスリーダー',
        },
        {
          quote: 'ローンチ準備のテンプレ化で毎月のリリース本数が2倍になりました。',
          name: '会員制コミュニティ運営 / 吉川様',
          role: 'マーケティング責任者',
        },
      ],
      backgroundColor: '#F0FDF4',
      textColor: '#065F46',
      accentColor: '#34D399',
    } as TestimonialsBlockContent,
  },
  {
    id: 'top-testimonials-amber',
    templateId: 'top-testimonials-1',
    name: 'お客様の声（アンバー）',
    category: 'trust',
    description: '温かみのあるアンバーカラーで成果の実感を強調。',
    defaultContent: {
      title: '利用者の成果',
      subtitle: '導入チームの声から、成長のプロセスをご覧ください。',
      testimonials: [
        {
          quote: 'ランディングページの改善サイクルが高速化し、CVRが1.8倍に。',
          name: 'オンラインスクール運営 / 山本様',
          role: '運用責任者',
        },
        {
          quote: 'AIコピー案が豊富で、制作時間を70%削減できました。',
          name: 'コンテンツマーケ企業 / 鈴木様',
          role: 'クリエイティブディレクター',
        },
      ],
      backgroundColor: '#FFF7ED',
      textColor: '#7C2D12',
      accentColor: '#F97316',
    } as TestimonialsBlockContent,
  },
  {
    id: 'top-testimonials-violet',
    templateId: 'top-testimonials-1',
    name: 'お客様の声（バイオレット）',
    category: 'trust',
    description: 'ラグジュアリーなバイオレットで高単価商材にも馴染む構成。',
    defaultContent: {
      title: 'クライアントレビュー',
      subtitle: 'プロフェッショナルな現場で選ばれた理由をご紹介。',
      testimonials: [
        {
          quote: 'ブランドトンマナを崩さずに世界観を統一できるのが決め手でした。',
          name: 'ハイエンドプロダクト / 井上様',
          role: 'ブランドマネージャー',
        },
        {
          quote: '編集モードが直感的で、社内ディレクターでも即日運用可能でした。',
          name: '代理店 / 松本様',
          role: '制作ディレクター',
        },
      ],
      backgroundColor: '#F5F3FF',
      textColor: '#4338CA',
      accentColor: '#A855F7',
    } as TestimonialsBlockContent,
  },
  {
    id: 'top-testimonials-slate',
    templateId: 'top-testimonials-1',
    name: 'お客様の声（モノトーン）',
    category: 'trust',
    description: 'ダークトーンで落ち着いた実績訴求ができるスタイル。',
    defaultContent: {
      title: 'クライアントの評価',
      subtitle: '導入プロジェクトの裏側をリアルに共有します。',
      testimonials: [
        {
          quote: 'テンプレートが軽量なので、スマホでも快適に動作し商談化につながりました。',
          name: 'コンサルティング会社 / 岡本様',
          role: '代表パートナー',
        },
        {
          quote: 'セクションごとにカラーを調整できるので、CI適用も簡単でした。',
          name: 'ITベンチャー / 林様',
          role: 'CMO',
        },
      ],
      backgroundColor: '#0F172A',
      textColor: '#F1F5F9',
      accentColor: '#64748B',
    } as TestimonialsBlockContent,
  },
  {
    id: 'top-faq-navy',
    templateId: 'top-faq-1',
    name: 'FAQ（ディープブルー）',
    category: 'content',
    description: '濃紺の背景で信頼感を与えるシンプルなFAQ。',
    defaultContent: {
      title: 'よくある質問',
      subtitle: '導入前によくいただく質問をまとめました。',
      items: [
        {
          question: '本当に最短5分でLPを公開できますか？',
          answer: 'AIヒアリングに回答すると構成とコピーが自動生成され、そのまま公開まで行えます。ドメイン設定や決済もワンクリックで完了します。',
        },
        {
          question: '決済や会員サイトは連携できますか？',
          answer: 'Stripe・メール配信・会員サイトへのWebhook連携を標準装備。APIキーを登録するだけで即日稼働できます。',
        },
      ],
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
      accentColor: '#38BDF8',
    } as FAQBlockContent,
  },
  {
    id: 'top-faq-sky',
    templateId: 'top-faq-1',
    name: 'FAQ（スカイグレー）',
    category: 'content',
    description: '淡いグレーブルーで軽やかに疑問を解消するスタイル。',
    defaultContent: {
      title: 'よくある質問',
      subtitle: '導入前に寄せられる代表的な質問をまとめました。',
      items: [
        {
          question: '無料トライアルの期間はどれくらいですか？',
          answer: '14日間すべての機能をお試しいただけます。終了後も自動課金はありません。',
        },
        {
          question: '契約後のサポート体制を教えてください。',
          answer: '専任カスタマーサクセスとコミュニティが伴走し、導入初月から成果創出を支援します。',
        },
      ],
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      accentColor: '#2563EB',
    } as FAQBlockContent,
  },
  {
    id: 'top-faq-mint',
    templateId: 'top-faq-1',
    name: 'FAQ（ミント）',
    category: 'content',
    description: 'ミントグリーンで爽やかに不安を解消するFAQ。',
    defaultContent: {
      title: 'よくあるご質問',
      subtitle: 'サポートチームが頻繁に受ける質問にお答えします。',
      items: [
        {
          question: 'テンプレートのカスタマイズは自由にできますか？',
          answer: 'カラーやコピーは完全に編集可能で、ノーコードで調整できます。',
        },
        {
          question: '決済連携は安全ですか？',
          answer: 'Stripeを採用し、PCI DSSに準拠したセキュアな決済体験を提供します。',
        },
      ],
      backgroundColor: '#ECFDF5',
      textColor: '#047857',
      accentColor: '#10B981',
    } as FAQBlockContent,
  },
  {
    id: 'top-faq-amber',
    templateId: 'top-faq-1',
    name: 'FAQ（サンド）',
    category: 'content',
    description: '柔らかなサンドカラーで温かみを演出するFAQ。',
    defaultContent: {
      title: 'サポートQ&A',
      subtitle: '導入を検討中の方から特に多いご質問。',
      items: [
        {
          question: '契約期間の縛りはありますか？',
          answer: '月額プランと年額プランから選択でき、いつでもプラン変更が可能です。',
        },
        {
          question: 'チームメンバーの招待は制限がありますか？',
          answer: 'プランごとに最大人数が異なりますが、追加購入で柔軟に拡張できます。',
        },
      ],
      backgroundColor: '#FFFBEB',
      textColor: '#92400E',
      accentColor: '#F59E0B',
    } as FAQBlockContent,
  },
  {
    id: 'top-faq-violet',
    templateId: 'top-faq-1',
    name: 'FAQ（バイオレット）',
    category: 'content',
    description: '淡いバイオレットで上質なブランド体験に馴染むFAQ。',
    defaultContent: {
      title: 'FAQ',
      subtitle: '高付加価値サービス向けによくある質問をまとめています。',
      items: [
        {
          question: 'ブランドフォントは適用できますか？',
          answer: 'フォントトークンを設定すれば、全ブロックで一括適用が可能です。',
        },
        {
          question: 'AIアシスタントは日本語にも対応していますか？',
          answer: '完全日本語対応で、質問に応じて最適なコピーを生成します。',
        },
      ],
      backgroundColor: '#F5F3FF',
      textColor: '#4C1D95',
      accentColor: '#A855F7',
    } as FAQBlockContent,
  },
  {
    id: 'top-pricing-sky',
    templateId: 'top-pricing-1',
    name: '価格表（スカイ）',
    category: 'conversion',
    description: 'ブルーベースで清潔感のある3プラン構成。',
    defaultContent: {
      title: 'プランと料金',
      subtitle: 'ローンチの規模に合わせて選べる柔軟なプランをご用意しています。',
      plans: [
        {
          name: 'スターター',
          price: '¥29,800',
          period: '/月',
          description: '個人〜小規模チーム向け。月4本までのローンチを高速化。',
          features: ['AIコピー生成', 'テンプレートライブラリ', '公開ホスティング', 'Stripe連携'],
          buttonText: '無料で始める',
        },
        {
          name: 'プロフェッショナル',
          price: '¥79,800',
          period: '/月',
          description: '本格的なローンチ運用に。チームコラボと分析機能を強化。',
          features: ['スタータープランの全機能', 'チーム編集・コメント', 'アクセス分析ダッシュボード', '優先サポート'],
          buttonText: '7日間トライアル',
          highlighted: true,
        },
        {
          name: 'エンタープライズ',
          price: '¥198,000',
          period: '/月',
          description: '年間ローンチ計画と売上管理を専任チームが伴走します。',
          features: ['専属CSチーム', 'Webhookカスタマイズ', 'KPIレポーティング', '広告クリエイティブ制作'],
          buttonText: '相談する',
        },
      ],
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      accentColor: '#2563EB',
      buttonColor: '#2563EB',
    } as PricingBlockContent,
  },
  {
    id: 'top-pricing-mint',
    templateId: 'top-pricing-1',
    name: '価格表（ミント）',
    category: 'conversion',
    description: 'ヘルスケアやウェルネス商材に合うミントトーンの価格表。',
    defaultContent: {
      title: 'プランと料金',
      subtitle: '利用規模に合わせて柔軟に選べる3つのプランをご用意。',
      plans: [
        {
          name: 'ライト',
          price: '¥24,800',
          period: '/月',
          description: '個人〜小規模チーム向け。月2本までのローンチをサポート。',
          features: ['AIコピー生成', 'テンプレート編集', '公開ホスティング', 'メールサポート'],
          buttonText: '無料トライアル',
        },
        {
          name: 'スタンダード',
          price: '¥59,800',
          period: '/月',
          description: 'チーム運用向け。共同編集と分析機能を強化。',
          features: ['ライトの全機能', 'チームメンバー5名', '分析ダッシュボード', '優先チャットサポート'],
          buttonText: '今すぐ申し込む',
          highlighted: true,
        },
        {
          name: 'グロース',
          price: '¥129,800',
          period: '/月',
          description: '本格的な成長フェーズ向け。施策伴走とAPI連携を提供。',
          features: ['カスタムドメイン', '専任CS', 'Slack連携', '月次レビュー'],
          buttonText: '相談する',
        },
      ],
      backgroundColor: '#ECFDF5',
      textColor: '#065F46',
      accentColor: '#10B981',
      buttonColor: '#10B981',
    } as PricingBlockContent,
  },
  {
    id: 'top-pricing-amber',
    templateId: 'top-pricing-1',
    name: '価格表（アンバー）',
    category: 'conversion',
    description: '高揚感のあるアンバーカラーで限定感を演出。',
    defaultContent: {
      title: '料金プラン',
      subtitle: '成果までの最短距離を選べる柔軟なプランをご用意しています。',
      plans: [
        {
          name: 'スターター',
          price: '¥32,800',
          period: '/月',
          description: 'ローンチ前の検証段階に最適。週1本の配信をサポート。',
          features: ['テンプレートライブラリ', 'AIコピー下書き', '公開ホスティング', 'メールサポート'],
          buttonText: '今すぐ始める',
        },
        {
          name: 'プロ',
          price: '¥89,800',
          period: '/月',
          description: '本格運用に最適なスタンダードプラン。',
          features: ['スターターの全機能', 'チームメンバー10名', 'アクセス分析', '優先オンボーディング'],
          buttonText: 'トライアル',
          highlighted: true,
        },
        {
          name: 'エリート',
          price: '¥198,000',
          period: '/月',
          description: 'スケールフェーズに特化した伴走プラン。',
          features: ['専任コンサル', '広告クリエイティブ', 'APIカスタマイズ', '月次ワークショップ'],
          buttonText: '相談する',
        },
      ],
      backgroundColor: '#FFFBEB',
      textColor: '#92400E',
      accentColor: '#F97316',
      buttonColor: '#F97316',
    } as PricingBlockContent,
  },
  {
    id: 'top-pricing-violet',
    templateId: 'top-pricing-1',
    name: '価格表（バイオレット）',
    category: 'conversion',
    description: 'ハイエンド領域向け。パープルで上質感を演出。',
    defaultContent: {
      title: 'Fee Structure',
      subtitle: '伴走レベルに応じて最適なパッケージをご提案します。',
      plans: [
        {
          name: 'Essential',
          price: '¥49,800',
          period: '/月',
          description: 'ブランドの世界観を崩さずにLPを高速制作。',
          features: ['ブランドカラートークン', 'ドラッグ&ドロップ編集', 'AIコピーガイド', 'メールサポート'],
          buttonText: 'Start Now',
        },
        {
          name: 'Professional',
          price: '¥109,800',
          period: '/月',
          description: '多チーム運用を想定したプロフェッショナルプラン。',
          features: ['Essentialの全機能', 'レビュー&承認フロー', '高度なアナリティクス', '専任オンボーディング'],
          buttonText: 'Book Demo',
          highlighted: true,
        },
        {
          name: 'Premier',
          price: '¥248,000',
          period: '/月',
          description: '成果コミット型の伴走サポートとカスタム開発を含む。',
          features: ['専任デザイナー', 'カスタムインテグレーション', '月次レビュー', '24hサポート'],
          buttonText: 'Talk to Sales',
        },
      ],
      backgroundColor: '#F5F3FF',
      textColor: '#4338CA',
      accentColor: '#8B5CF6',
      buttonColor: '#8B5CF6',
    } as PricingBlockContent,
  },
  {
    id: 'top-pricing-slate',
    templateId: 'top-pricing-1',
    name: '価格表（モノトーン）',
    category: 'conversion',
    description: 'ダークトーンで重厚かつモダンな価格提示が可能。',
    defaultContent: {
      title: 'プラン一覧',
      subtitle: 'ハイパフォーマンスな制作体制を月額で提供します。',
      plans: [
        {
          name: 'Launch',
          price: '¥39,800',
          period: '/月',
          description: 'ローンチ初期に必要な基本セットを網羅。',
          features: ['テンプレート無制限', 'AIコピー生成', '公開ホスティング', 'メールサポート'],
          buttonText: '無料で試す',
        },
        {
          name: 'Scale',
          price: '¥98,000',
          period: '/月',
          description: 'チーム運用と自動化を強化するスケールプラン。',
          features: ['Launchの全機能', 'チーム共同編集', 'パフォーマンス分析', '優先サポート'],
          buttonText: '導入を相談',
          highlighted: true,
        },
        {
          name: 'Enterprise',
          price: '¥238,000',
          period: '/月',
          description: '大規模組織向けのカスタムソリューション。',
          features: ['専任オンボーディング', 'SLA保証', 'カスタムAPI', 'グローバルサポート'],
          buttonText: '詳細を問い合わせ',
        },
      ],
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
      accentColor: '#38BDF8',
      buttonColor: '#38BDF8',
    } as PricingBlockContent,
  },
  {
    id: 'top-problem-sky',
    templateId: 'top-problem-1',
    name: '課題提起（スカイ）',
    category: 'content',
    description: 'ライトなブルートーンで課題認識を整理するブロック。',
    defaultContent: {
      title: 'こんなお悩みはありませんか？',
      subtitle: '情報を届けたいのに、ローンチ準備が複雑すぎると諦めていませんか。',
      problems: [
        '構成やコピーをゼロから考える時間がない',
        'デザイン調整とコーディングで徹夜続き',
        '決済連携や会員エリアの仕組み化が難しい',
        '旬な情報を出したいのに公開までが遅い',
      ],
      backgroundColor: '#FFFFFF',
      textColor: '#0F172A',
      accentColor: '#2563EB',
    } as ProblemBlockContent,
  },
  {
    id: 'top-problem-mint',
    templateId: 'top-problem-1',
    name: '課題提起（ミント）',
    category: 'content',
    description: '爽やかなミントカラーで課題をポジティブに整理。',
    defaultContent: {
      title: 'こんなお悩みありませんか？',
      subtitle: '導入前に誰もが抱えがちな課題をチェックしてみましょう。',
      problems: [
        '広告経由のリードが増えない',
        'コンテンツ制作のリソースが足りない',
        'デザイン調整に毎回時間がかかる',
        '社内でナレッジが共有されない',
      ],
      backgroundColor: '#ECFDF5',
      textColor: '#065F46',
      accentColor: '#10B981',
    } as ProblemBlockContent,
  },
  {
    id: 'top-problem-amber',
    templateId: 'top-problem-1',
    name: '課題提起（アンバー）',
    category: 'content',
    description: '温かみのあるアンバーで緊張を和らげつつ課題を提示。',
    defaultContent: {
      title: 'よくある課題',
      subtitle: '改善前のボトルネックを洗い出してみましょう。',
      problems: [
        '制作進行の指示が属人化している',
        '毎回ゼロから構成を考えている',
        '公開スピードが遅く機会損失が発生',
        'データ分析ができず改善に繋がらない',
      ],
      backgroundColor: '#FFF7ED',
      textColor: '#7C2D12',
      accentColor: '#F97316',
    } as ProblemBlockContent,
  },
  {
    id: 'top-problem-violet',
    templateId: 'top-problem-1',
    name: '課題提起（バイオレット）',
    category: 'content',
    description: '上質なトーンで高単価商材にもマッチする課題提起。',
    defaultContent: {
      title: 'Beforeの状態を可視化',
      subtitle: '導入前に多くの企業が抱えていた課題を整理しました。',
      problems: [
        '複数プロジェクトで品質がばらつく',
        '外部パートナーへの依存が高い',
        'CTA設計に一貫性がない',
        'ナレッジ共有が属人的',
      ],
      backgroundColor: '#F5F3FF',
      textColor: '#4C1D95',
      accentColor: '#A855F7',
    } as ProblemBlockContent,
  },
  {
    id: 'top-problem-slate',
    templateId: 'top-problem-1',
    name: '課題提起（モノトーン）',
    category: 'content',
    description: 'ダークトーンで課題の深刻さと信頼性を訴求。',
    defaultContent: {
      title: '課題の棚卸し',
      subtitle: '現状の課題を整理することで最適なロードマップが描けます。',
      problems: [
        '制作フローが可視化されていない',
        'マーケ施策が点で終わってしまう',
        'スマホ表示で離脱が増えている',
        'ブランドトンマナの統一が難しい',
      ],
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
      accentColor: '#38BDF8',
    } as ProblemBlockContent,
  },
  {
    id: 'top-before-after-navy',
    templateId: 'top-before-after-1',
    name: 'ビフォーアフター（ディープブルー）',
    category: 'content',
    description: 'ダークトーンでインパクトのあるビフォーアフター。',
    defaultContent: {
      title: '導入前と導入後の変化',
      before: {
        label: 'Before',
        description: '毎回ローンチごとに構成作りとデザインで徹夜。公開までに最低でも2週間はかかっていた。',
      },
      after: {
        label: 'After',
        description: 'AIが構成とコピーを自動生成。チーム3名で週1本のローンチを回せる体制に。',
      },
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
      accentColor: '#38BDF8',
    } as BeforeAfterBlockContent,
  },
  {
    id: 'top-before-after-sky',
    templateId: 'top-before-after-1',
    name: 'ビフォーアフター（スカイ）',
    category: 'content',
    description: 'クリーンなブルートーンで変化を分かりやすく伝える。',
    defaultContent: {
      title: '導入前と導入後の変化',
      before: {
        label: 'Before',
        description: '毎回の制作ディレクションに工数がかかり、公開までに2〜3週間を要していた。',
      },
      after: {
        label: 'After',
        description: 'テンプレートとAI支援で3日以内に公開。テストと改善が高速に回るように。',
      },
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      accentColor: '#2563EB',
    } as BeforeAfterBlockContent,
  },
  {
    id: 'top-before-after-mint',
    templateId: 'top-before-after-1',
    name: 'ビフォーアフター（ミント）',
    category: 'content',
    description: 'ヘルシーなミントカラーで前後比較を柔らかく訴求。',
    defaultContent: {
      title: '改善インパクト',
      before: {
        label: 'Before',
        description: 'ノウハウが属人化し、チームで制作するたびに品質が揺らいでいた。',
      },
      after: {
        label: 'After',
        description: 'コンポーネント化で誰でも同じ品質を再現。品質レビュー時間を半減。',
      },
      backgroundColor: '#ECFDF5',
      textColor: '#065F46',
      accentColor: '#10B981',
    } as BeforeAfterBlockContent,
  },
  {
    id: 'top-before-after-amber',
    templateId: 'top-before-after-1',
    name: 'ビフォーアフター（アンバー）',
    category: 'content',
    description: 'アンバーカラーでスピード感と熱量を演出。',
    defaultContent: {
      title: '成果のギャップ',
      before: {
        label: 'Before',
        description: 'ローンチごとに制作コストが膨らみ、黒字化まで時間を要していた。',
      },
      after: {
        label: 'After',
        description: '共通ブロックを活用し、制作コストを65%削減。月次ローンチが定着。',
      },
      backgroundColor: '#FFF7ED',
      textColor: '#7C2D12',
      accentColor: '#F97316',
    } as BeforeAfterBlockContent,
  },
  {
    id: 'top-before-after-slate',
    templateId: 'top-before-after-1',
    name: 'ビフォーアフター（モノトーン）',
    category: 'content',
    description: 'モノトーンとブルーグレーで落ち着いた印象の比較。',
    defaultContent: {
      title: 'Before / After',
      before: {
        label: 'Before',
        description: 'スマホ表示時に表示崩れが多く、離脱率が高かった。',
      },
      after: {
        label: 'After',
        description: 'レスポンシブ最適化で読みやすさが向上。滞在時間が32%アップ。',
      },
      backgroundColor: '#111827',
      textColor: '#F8FAFC',
      accentColor: '#94A3B8',
    } as BeforeAfterBlockContent,
  },
  {
    id: 'top-bonus-sky',
    templateId: 'top-bonus-1',
    name: '特典（スカイ）',
    category: 'conversion',
    description: '爽やかなブルートーンで特典価値を訴求。',
    defaultContent: {
      title: '今だけの参加特典',
      subtitle: '成果までの距離を一気に縮める特典を期間限定でご提供します。',
      totalValue: '合計109,800円相当',
      bonuses: [
        {
          title: '特典1：即実践ローンチテンプレ集',
          description: '成功事例をベースにした構成・コピー例を30種収録。',
          value: '29,800円相当',
        },
        {
          title: '特典2：AIコピー生成クレジット',
          description: '月間300クレジットを無償提供。キャッチコピー量産が可能に。',
          value: '39,800円相当',
        },
      ],
      backgroundColor: '#EBF4FF',
      textColor: '#0F172A',
      accentColor: '#2563EB',
    } as BonusListBlockContent,
  },
  {
    id: 'top-bonus-mint',
    templateId: 'top-bonus-1',
    name: '特典（ミント）',
    category: 'conversion',
    description: '透明感のあるミントカラーで柔らかさと信頼感を演出。',
    defaultContent: {
      title: '参加特典',
      subtitle: '導入直後から成果を出すための特典を無償提供。',
      totalValue: '合計128,000円相当',
      bonuses: [
        {
          title: '特典1：ローンチ戦略カレンダー',
          description: '90日分の配信プランとチェックリストをセットでお届け。',
          value: '39,800円相当',
        },
        {
          title: '特典2：AIコピー生成クレジット',
          description: '初月限定で500クレジット分のコピー生成が利用可能。',
          value: '49,800円相当',
        },
      ],
      backgroundColor: '#ECFDF5',
      textColor: '#065F46',
      accentColor: '#10B981',
    } as BonusListBlockContent,
  },
  {
    id: 'top-bonus-amber',
    templateId: 'top-bonus-1',
    name: '特典（アンバー）',
    category: 'conversion',
    description: 'アンバーグラデーションで限定感と高揚感を高める。',
    defaultContent: {
      title: '限定特典',
      subtitle: '今だけの参加者限定でスペシャルコンテンツをご用意しました。',
      totalValue: '合計156,000円相当',
      bonuses: [
        {
          title: '特典1：ローンチテンプレート完全セット',
          description: '実績のある構成とコピーを20パターン収録。',
          value: '59,800円相当',
        },
        {
          title: '特典2：オンボーディング伴走プログラム',
          description: '専任CSが初回ローンチまで伴走する個別プログラム。',
          value: '69,800円相当',
        },
      ],
      backgroundColor: '#FFFBEB',
      textColor: '#7C2D12',
      accentColor: '#F97316',
    } as BonusListBlockContent,
  },
  {
    id: 'top-bonus-violet',
    templateId: 'top-bonus-1',
    name: '特典（バイオレット）',
    category: 'conversion',
    description: '研ぎ澄まされたバイオレットでプレミアム感を演出。',
    defaultContent: {
      title: 'Enrollment Bonus',
      subtitle: '今すぐ実践に移せるプレミアム特典をご用意しました。',
      totalValue: 'Total Value ¥178,000',
      bonuses: [
        {
          title: 'Bonus 01: Creative Blueprint',
          description: 'ハイエンド領域の成功事例をまとめたデザインガイド。',
          value: '¥68,000 value',
        },
        {
          title: 'Bonus 02: Concierge Support',
          description: '72時間以内に課題を解決するプレミアムサポート。',
          value: '¥88,000 value',
        },
      ],
      backgroundColor: '#F5F3FF',
      textColor: '#4C1D95',
      accentColor: '#A855F7',
    } as BonusListBlockContent,
  },
  {
    id: 'top-bonus-slate',
    templateId: 'top-bonus-1',
    name: '特典（モノトーン）',
    category: 'conversion',
    description: 'モノトーンで落ち着いた高級感を演出する特典紹介。',
    defaultContent: {
      title: '特典ラインナップ',
      subtitle: 'プログラム参加者限定で充実の支援コンテンツをご提供。',
      totalValue: '合計198,000円相当',
      bonuses: [
        {
          title: '特典1：ハイコンバージョン設計書',
          description: 'CV向上のための構成・コピー・CTA設計テンプレート。',
          value: '89,800円相当',
        },
        {
          title: '特典2：ローンチ分析レポート',
          description: '成功事例のデータを集約した改善ガイドブック。',
          value: '54,000円相当',
        },
      ],
      backgroundColor: '#111827',
      textColor: '#F8FAFC',
      accentColor: '#38BDF8',
    } as BonusListBlockContent,
  },
  {
    id: 'top-guarantee-night',
    templateId: 'top-guarantee-1',
    name: '保証（ナイト）',
    category: 'trust',
    description: '深いネイビートーンで返金保証を強調。',
    defaultContent: {
      title: '30日間 全額返金保証',
      subtitle: 'リスクゼロで体験いただくために、安心の保証制度を用意しています。',
      guaranteeDetails: '条件は一切ありません。実際に使ってみてご満足いただけなければ、メール一本で全額返金いたします。',
      badgeText: 'Risk Free',
      bulletPoints: [
        '専任サポートが導入〜初回ローンチまで伴走',
        '再現性の高いAIプロンプトテンプレート付き',
        '返金サポート専用窓口を24時間以内に対応',
      ],
      backgroundColor: '#020617',
      textColor: '#E2E8F0',
      accentColor: '#34D399',
    } as GuaranteeBlockContent,
  },
  {
    id: 'top-guarantee-sky',
    templateId: 'top-guarantee-1',
    name: '保証（スカイ）',
    category: 'trust',
    description: 'クリーンなブルートーンで保証の安心感を訴求。',
    defaultContent: {
      title: '30日間の全額返金保証',
      subtitle: 'お申し込みから30日以内なら、理由を問わず返金を承ります。',
      guaranteeDetails: '初回ローンチを実施して成果が得られなかった場合、メール1通で返金を申請できます。手数料は一切かかりません。',
      badgeText: 'Risk Free',
      bulletPoints: [
        '導入オンボーディングを専任CSがサポート',
        'プロジェクト設計テンプレートを全員に配布',
        'サポートチームが24時間以内に回答',
      ],
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
      accentColor: '#38BDF8',
    } as GuaranteeBlockContent,
  },
  {
    id: 'top-guarantee-mint',
    templateId: 'top-guarantee-1',
    name: '保証（ミント）',
    category: 'trust',
    description: '柔らかなミントカラーで安心を訴求する保証ブロック。',
    defaultContent: {
      title: '安心の返金保証',
      subtitle: '安心してご利用いただけるよう、初月はリスクゼロでお試しいただけます。',
      guaranteeDetails: '導入から30日以内であれば、使用状況に関わらず全額返金いたします。',
      badgeText: '安心サポート',
      bulletPoints: [
        '導入前カウンセリングを無料提供',
        '返金依頼はチャットからいつでも受付',
        '返金後もデータは安全に破棄',
      ],
      backgroundColor: '#ECFDF5',
      textColor: '#047857',
      accentColor: '#10B981',
    } as GuaranteeBlockContent,
  },
  {
    id: 'top-guarantee-amber',
    templateId: 'top-guarantee-1',
    name: '保証（アンバー）',
    category: 'trust',
    description: 'アンバートーンで情熱と安心を同時にアピール。',
    defaultContent: {
      title: '返金保証制度',
      subtitle: '結果に納得いただけない場合は、申請だけで全額返金いたします。',
      guaranteeDetails: 'サポートチームと伴走した上で成果が出なかった場合、契約初月の利用料を全額返金します。',
      badgeText: 'Guarantee',
      bulletPoints: [
        '返金時もサポート担当が手続き支援',
        '返金後も問題点のフィードバックを共有',
        '継続利用の押し売りは一切なし',
      ],
      backgroundColor: '#FFFBEB',
      textColor: '#92400E',
      accentColor: '#F59E0B',
    } as GuaranteeBlockContent,
  },
  {
    id: 'top-guarantee-violet',
    templateId: 'top-guarantee-1',
    name: '保証（バイオレット）',
    category: 'trust',
    description: 'プレミアムなバイオレットで高付加価値商材にマッチ。',
    defaultContent: {
      title: 'Premium Assurance',
      subtitle: '安心してご導入いただけるよう、プレミアム保証をご用意しています。',
      guaranteeDetails: 'ご導入から45日以内に成果が得られなかった場合は、100%返金いたします。',
      badgeText: 'Premium Care',
      bulletPoints: [
        '専任コンシェルジュが返金申請をサポート',
        '返金後もナレッジ資料を30日閲覧可能',
        '解約アンケートで改善要望を反映',
      ],
      backgroundColor: '#F5F3FF',
      textColor: '#4C1D95',
      accentColor: '#A855F7',
    } as GuaranteeBlockContent,
  },
  {
    id: 'top-guarantee-slate',
    templateId: 'top-guarantee-1',
    name: '保証（モノトーン）',
    category: 'trust',
    description: 'モノトーンで落ち着いた信頼感を醸成する保証ブロック。',
    defaultContent: {
      title: '返金保証ポリシー',
      subtitle: '導入後30日以内であれば、全額返金に対応いたします。',
      guaranteeDetails: 'フォームから申請いただくだけで、3営業日以内に返金手続きを進めます。',
      badgeText: 'Secure',
      bulletPoints: [
        '契約期間に関わらず申請可能',
        '返金時の手数料は弊社が負担',
        '担当者が継続的にフォロー',
      ],
      backgroundColor: '#111827',
      textColor: '#E2E8F0',
      accentColor: '#94A3B8',
    } as GuaranteeBlockContent,
  },
  {
    id: 'top-countdown-red',
    templateId: 'top-countdown-1',
    name: 'カウントダウン（レッド）',
    category: 'urgency',
    description: '緊急感のあるレッドで締切を強調。',
    defaultContent: {
      title: '特別オファー終了まで',
      urgencyText: '締切までに参加いただいた方限定で、追加特典と返金保証をご提供します。',
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      backgroundColor: '#DC2626',
      textColor: '#FFFFFF',
      accentColor: '#F97316',
    } as CountdownBlockContent,
  },
  {
    id: 'top-countdown-navy',
    templateId: 'top-countdown-1',
    name: 'カウントダウン（ネイビー）',
    category: 'urgency',
    description: '落ち着いたネイビートーンで締切をスマートに訴求。',
    defaultContent: {
      title: '申込み締切まで',
      urgencyText: '現行特典は締切までの申込み分に限り適用されます。お早めにどうぞ。',
      targetDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
      accentColor: '#38BDF8',
    } as CountdownBlockContent,
  },
  {
    id: 'top-countdown-mint',
    templateId: 'top-countdown-1',
    name: 'カウントダウン（ミント）',
    category: 'urgency',
    description: '爽やかなミントカラーでポジティブに締切を案内。',
    defaultContent: {
      title: '登録締切まで',
      urgencyText: '定員に達し次第受付終了となります。残席わずかです。',
      targetDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      backgroundColor: '#0F766E',
      textColor: '#ECFDF5',
      accentColor: '#34D399',
    } as CountdownBlockContent,
  },
  {
    id: 'top-countdown-amber',
    templateId: 'top-countdown-1',
    name: 'カウントダウン（アンバー）',
    category: 'urgency',
    description: 'アンバーカラーでエネルギッシュに締切を伝える。',
    defaultContent: {
      title: '限定オファー終了まで',
      urgencyText: '今だけの限定価格と特典は締切日時で終了します。',
      targetDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
      backgroundColor: '#B45309',
      textColor: '#FEF3C7',
      accentColor: '#F97316',
    } as CountdownBlockContent,
  },
  {
    id: 'top-countdown-violet',
    templateId: 'top-countdown-1',
    name: 'カウントダウン（バイオレット）',
    category: 'urgency',
    description: '上品なバイオレットで高単価オファーに馴染む緊急訴求。',
    defaultContent: {
      title: 'Special Offer Ends In',
      urgencyText: '限定特典付きの申込はタイマー終了と同時にクローズします。',
      targetDate: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
      backgroundColor: '#4C1D95',
      textColor: '#F5F3FF',
      accentColor: '#C084FC',
    } as CountdownBlockContent,
  },
  {
    id: 'top-countdown-slate',
    templateId: 'top-countdown-1',
    name: 'カウントダウン（モノトーン）',
    category: 'urgency',
    description: 'モノトーンでスタイリッシュに締切を通知。',
    defaultContent: {
      title: '次回締切まで',
      urgencyText: 'スロットが埋まり次第受付終了となります。',
      targetDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      backgroundColor: '#111827',
      textColor: '#E2E8F0',
      accentColor: '#94A3B8',
    } as CountdownBlockContent,
  },
  {
    id: 'top-inline-cta-sky',
    templateId: 'top-inline-cta-1',
    name: 'インラインCTA（スカイ）',
    category: 'conversion',
    description: 'ブルートーンで汎用性の高いインラインCTA。',
    defaultContent: {
      eyebrow: '限定プログラム',
      title: '今すぐAIローンチを体験する',
      subtitle: 'アカウント作成から公開までを最短5分で完了。初月の成果創出まで伴走します。',
      buttonText: '無料で始める',
      buttonUrl: '/register',
      backgroundColor: '#FFFFFF',
      textColor: '#0F172A',
      accentColor: '#2563EB',
      buttonColor: '#2563EB',
    } as InlineCTABlockContent,
  },
  {
    id: 'top-inline-cta-mint',
    templateId: 'top-inline-cta-1',
    name: 'インラインCTA（ミント）',
    category: 'conversion',
    description: 'ミントカラーで柔らかく訴求するインラインCTA。',
    defaultContent: {
      eyebrow: '限定プログラム',
      title: '今すぐAIローンチを体験する',
      subtitle: 'ミッションに合わせたテンプレートを選ぶだけで、5分後には公開準備が整います。',
      buttonText: '体験してみる',
      buttonUrl: '/trial',
      backgroundColor: '#ECFDF5',
      textColor: '#065F46',
      accentColor: '#10B981',
      buttonColor: '#10B981',
    } as InlineCTABlockContent,
  },
  {
    id: 'top-inline-cta-amber',
    templateId: 'top-inline-cta-1',
    name: 'インラインCTA（アンバー）',
    category: 'conversion',
    description: '温かみのあるアンバーで緊急感を演出。',
    defaultContent: {
      eyebrow: 'Limited Offer',
      title: '今月限定で導入サポート無料',
      subtitle: '期間中のお申し込みで、初回ローンチの設計と実装を無償で支援します。',
      buttonText: '枠を確保する',
      buttonUrl: '/reserve',
      backgroundColor: '#FFF7ED',
      textColor: '#7C2D12',
      accentColor: '#F97316',
      buttonColor: '#F97316',
    } as InlineCTABlockContent,
  },
  {
    id: 'top-inline-cta-violet',
    templateId: 'top-inline-cta-1',
    name: 'インラインCTA（バイオレット）',
    category: 'conversion',
    description: 'ラグジュアリートーンで高価格帯のCTAに最適。',
    defaultContent: {
      eyebrow: 'Premium Access',
      title: 'ブランド体験の次のステップへ',
      subtitle: '世界観を保ちながら成果につなげるプレミアムテンプレートをご提供します。',
      buttonText: 'コンサルを予約する',
      buttonUrl: '/consulting',
      backgroundColor: '#F5F3FF',
      textColor: '#4C1D95',
      accentColor: '#A855F7',
      buttonColor: '#A855F7',
    } as InlineCTABlockContent,
  },
  {
    id: 'top-inline-cta-slate',
    templateId: 'top-inline-cta-1',
    name: 'インラインCTA（モノトーン）',
    category: 'conversion',
    description: 'モノトーンとブルーグレーで落ち着いた誘導を実現。',
    defaultContent: {
      eyebrow: 'Join the Network',
      title: 'コミュニティでローンチを加速',
      subtitle: '成功事例とノウハウ共有を通じて最短距離で成果を創出しましょう。',
      buttonText: 'コミュニティに参加する',
      buttonUrl: '/community',
      backgroundColor: '#111827',
      textColor: '#E2E8F0',
      accentColor: '#94A3B8',
      buttonColor: '#94A3B8',
    } as InlineCTABlockContent,
  },
  {
    id: 'top-media-spotlight-default',
    templateId: 'top-media-spotlight-1',
    name: 'メディアスポットライト',
    category: 'content',
    description: 'ユーザーがアップロードした画像と解説を軽量に配置できるブロック。',
    defaultContent: {
      tagline: 'Project Highlight',
      title: '制作の裏側から見えた成功プロセスを公開',
      subtitle: 'コンテンツ制作・公開・分析までをワンストップで行うチームの事例をご紹介します。',
      caption: 'Photo: In-house creative team / 2024',
      buttonText: '詳しく見る',
      buttonUrl: '/case-study',
      imageUrl: '',
      imageAlt: 'プロジェクト画像',
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      accentColor: '#2563EB',
      buttonColor: '#2563EB',
    } as MediaSpotlightBlockContent,
  },
];

export const INFO_PRODUCT_BLOCKS: TemplateBlock[] = [];

export const TEMPLATE_CATEGORIES = [
  { id: 'header', name: 'ヒーロー', icon: 'Hero' },
  { id: 'content', name: 'コンテンツ', icon: 'Content' },
  { id: 'conversion', name: 'コンバージョン', icon: 'Conversion' },
  { id: 'trust', name: '信頼・実績', icon: 'Trust' },
  { id: 'urgency', name: '緊急性', icon: 'Urgency' },
];

export function getTemplatesByCategory(category: string) {
  const allTemplates = [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS, ...CONTACT_BLOCKS, ...TOKUSHO_BLOCKS, ...NEWSLETTER_BLOCKS];
  return allTemplates.filter((template) => template.category === category);
}

export function getTemplateById(templateId: string) {
  const allTemplates = [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS, ...CONTACT_BLOCKS, ...TOKUSHO_BLOCKS, ...NEWSLETTER_BLOCKS];
  return allTemplates.find((template) => template.templateId === templateId);
}

export function getAllTemplates() {
  return [...TEMPLATE_LIBRARY, ...INFO_PRODUCT_BLOCKS, ...CONTACT_BLOCKS, ...TOKUSHO_BLOCKS, ...NEWSLETTER_BLOCKS];
}

// 特定商取引法ブロック（新規追加）
export const TOKUSHO_BLOCKS: TemplateBlock[] = [
  {
    id: 'top-tokusho-modern',
    templateId: 'top-tokusho-1',
    name: '特定商取引法（モダン）',
    category: 'content',
    description: 'モダンなカード形式の特商法表記。各項目の表示/非表示を自由に設定可能。',
    defaultContent: {
      title: '特定商取引法に基づく表記',
      subtitle: 'Legal Information',
      items: [
        {
          label: '販売業者名',
          value: '株式会社〇〇〇〇',
          icon: 'building',
          show: true,
        },
        {
          label: '代表者名',
          value: '山田 太郎',
          icon: 'user',
          show: true,
        },
        {
          label: '所在地',
          value: '〒123-4567\n東京都渋谷区〇〇 1-2-3\n〇〇ビル 4F',
          icon: 'map',
          show: true,
        },
        {
          label: '電話番号',
          value: '03-1234-5678\n（受付時間：平日10:00-18:00）',
          icon: 'phone',
          show: true,
        },
        {
          label: 'メールアドレス',
          value: 'info@example.com',
          icon: 'email',
          show: true,
        },
        {
          label: '販売価格',
          value: '各商品ページをご参照ください',
          icon: 'yen',
          show: true,
        },
        {
          label: '商品代金以外の料金',
          value: '消費税、送料、振込手数料',
          icon: 'card',
          show: true,
        },
        {
          label: '支払方法',
          value: 'クレジットカード決済\n銀行振込\nコンビニ決済',
          icon: 'banknotes',
          show: true,
        },
        {
          label: '支払時期',
          value: '各決済方法により異なります\nクレジットカード：即時\n銀行振込：ご注文後7日以内',
          icon: 'clock',
          show: true,
        },
        {
          label: '商品引渡時期',
          value: 'デジタルコンテンツ：決済確認後即時\n物理商品：入金確認後3-7営業日以内に発送',
          icon: 'truck',
          show: true,
        },
        {
          label: '返品・交換について',
          value: 'デジタルコンテンツの性質上、原則として返品・返金はお受けできません。\n不良品の場合は、商品到着後7日以内にご連絡ください。',
          icon: 'refresh',
          show: true,
        },
      ],
      backgroundColor: '#F9FAFB',
      textColor: '#111827',
      cardBackgroundColor: '#FFFFFF',
      borderColor: '#E5E7EB',
    } as TokushoBlockContent,
  },
  {
    id: 'top-tokusho-minimal',
    templateId: 'top-tokusho-1',
    name: '特定商取引法（ミニマル）',
    category: 'content',
    description: '必要最小限の項目のみ表示したシンプルな特商法表記。',
    defaultContent: {
      title: '特定商取引法に基づく表記',
      subtitle: 'Legal Notice',
      items: [
        {
          label: '販売業者名',
          value: '株式会社〇〇〇〇',
          icon: 'building',
          show: true,
        },
        {
          label: '代表者名',
          value: '山田 太郎',
          icon: 'user',
          show: true,
        },
        {
          label: '所在地',
          value: '〒123-4567 東京都渋谷区〇〇 1-2-3',
          icon: 'map',
          show: true,
        },
        {
          label: '電話番号',
          value: '03-1234-5678',
          icon: 'phone',
          show: false,
        },
        {
          label: 'メールアドレス',
          value: 'info@example.com',
          icon: 'email',
          show: true,
        },
        {
          label: '販売価格',
          value: '商品ページに記載',
          icon: 'yen',
          show: true,
        },
        {
          label: '支払方法',
          value: 'クレジットカード決済',
          icon: 'banknotes',
          show: true,
        },
        {
          label: '返品について',
          value: 'デジタルコンテンツのため返品不可',
          icon: 'refresh',
          show: true,
        },
      ],
      backgroundColor: '#FFFFFF',
      textColor: '#1F2937',
      cardBackgroundColor: '#F9FAFB',
      borderColor: '#D1D5DB',
    } as TokushoBlockContent,
  },
];

// お問い合わせブロック（新規追加）
export const CONTACT_BLOCKS: TemplateBlock[] = [
  {
    id: 'top-contact-line',
    templateId: 'top-contact-1',
    name: 'お問い合わせ（LINE）',
    category: 'conversion',
    description: 'LINEへの誘導に最適化されたお問い合わせブロック。営業時間や説明文をカスタマイズ可能。',
    defaultContent: {
      title: 'お問い合わせはこちら',
      subtitle: 'Contact Us',
      description: '営業時間は平日10:00-18:00です。お気軽にご連絡ください。',
      buttonText: 'LINEで問い合わせる',
      buttonUrl: 'https://line.me/R/ti/p/@example',
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      buttonColor: '#06C755',
      buttonTextColor: '#FFFFFF',
    } as ContactBlockContent,
  },
  {
    id: 'top-contact-newsletter',
    templateId: 'top-contact-1',
    name: 'お問い合わせ（メルマガ）',
    category: 'conversion',
    description: 'メルマガ登録フォームへの誘導に最適化されたブロック。',
    defaultContent: {
      title: 'メルマガ購読はこちら',
      subtitle: 'Newsletter',
      description: '最新情報やお得なキャンペーン情報を週1回お届けします。',
      buttonText: 'メルマガに登録する',
      buttonUrl: 'https://example.com/newsletter',
      backgroundColor: '#EFF6FF',
      textColor: '#1E3A8A',
      buttonColor: '#2563EB',
      buttonTextColor: '#FFFFFF',
    } as ContactBlockContent,
  },
  {
    id: 'top-contact-form',
    templateId: 'top-contact-1',
    name: 'お問い合わせ（フォーム）',
    category: 'conversion',
    description: 'お問い合わせフォームへの誘導。シンプルで汎用性の高いデザイン。',
    defaultContent: {
      title: 'お問い合わせ',
      subtitle: 'Get in Touch',
      description: 'ご質問・ご相談はお気軽にお問い合わせください。24時間以内にご返信いたします。',
      buttonText: 'お問い合わせフォーム',
      buttonUrl: 'https://example.com/contact',
      backgroundColor: '#FFFFFF',
      textColor: '#111827',
      buttonColor: '#10B981',
      buttonTextColor: '#FFFFFF',
    } as ContactBlockContent,
  },
];

// メルマガ購読ブロック（新規追加）
export const NEWSLETTER_BLOCKS: TemplateBlock[] = [
  {
    id: 'top-newsletter-blue',
    templateId: 'top-newsletter-1',
    name: 'メルマガ購読（ブルー）',
    category: 'conversion',
    description: '美しいメルマガ購読申込ブロック。説明文とボタンを自由にカスタマイズ可能。',
    defaultContent: {
      title: 'メールマガジン',
      description: 'ただ今お得なメルマガ配信中です！下記のボタンをクリックして今すぐお使いのメールアドレスをご入力ください',
      buttonText: 'メルマガ購読',
      buttonUrl: 'https://example.com/newsletter',
      backgroundColor: '#EFF6FF',
      textColor: '#1E3A8A',
      buttonColor: '#2563EB',
      buttonTextColor: '#FFFFFF',
    } as NewsletterBlockContent,
  },
  {
    id: 'top-newsletter-green',
    templateId: 'top-newsletter-1',
    name: 'メルマガ購読（グリーン）',
    category: 'conversion',
    description: 'グリーンカラーのメルマガ購読ブロック。信頼感と安心感を演出。',
    defaultContent: {
      title: '最新情報をお届け',
      description: '最新のお得な情報やキャンペーンをいち早くお届けします。今すぐ無料登録してください！',
      buttonText: '今すぐ登録',
      buttonUrl: 'https://example.com/subscribe',
      backgroundColor: '#ECFDF5',
      textColor: '#065F46',
      buttonColor: '#10B981',
      buttonTextColor: '#FFFFFF',
    } as NewsletterBlockContent,
  },
  {
    id: 'top-newsletter-purple',
    templateId: 'top-newsletter-1',
    name: 'メルマガ購読（パープル）',
    category: 'conversion',
    description: 'プレミアム感のあるパープルカラー。高級商材向け。',
    defaultContent: {
      title: 'VIP会員限定情報',
      description: '特別なあなただけにお届けする、プレミアムな情報をメールマガジンで配信しています。',
      buttonText: 'VIP登録する',
      buttonUrl: 'https://example.com/vip-newsletter',
      backgroundColor: '#FAF5FF',
      textColor: '#6B21A8',
      buttonColor: '#9333EA',
      buttonTextColor: '#FFFFFF',
    } as NewsletterBlockContent,
  },
];
